### ISSUE TITLE
cachecloud是客户端和redis的代理吗？

### ISSUE THREAD

**Issue by sohutv** [sohutv/cachecloud#1]
cachecloud是客户端和redis的代理吗？

**Comment by carlosfu** [comment]
并不是，客户端只有只有启动时，需要从cachecloud拉一下redis的实例地址，如果没有开通上报功能，直到下次启动前就不需要与cachecloud进行交互了，所以访问redis并没有任何损耗。

**Comment by SoyeeDst** [comment]
有没考虑把Codis类似的功能集成进来，让Redis进行实例分片？

**Comment by carlosfu** [comment]
> 有没考虑把Codis类似的功能集成进来，让Redis进行实例分片？

我们使用的是redis3.0的cluster分片方案，相当靠谱

codis也是很优秀的架构，但是我们这方面没有相关经验，暂时只使用官方版本。

以后如果有需要可以考虑的。多谢关注。

**Comment by chengxuxinshou** [comment]
当客户端启动从cachecloud拉数据时候，建议在本地持久化一份链接信息副本，这样保证下次启动客户端时，即使因为各种情况导致无法拉取配置，也能有读取本地副本文件作为容灾方案。

**Comment by carlosfu** [comment]
> 当客户端启动从cachecloud拉数据时候，建议在本地持久化一份链接信息副本，这样保证下次启动客户端时，即使因为各种情况导致无法拉取配置，也能有读取本地副本文件作为容灾方案。

不做这个是为了防止本地脏数据，因为在运维的过程中，有可能节点、节点之间的关系都会发生变化。
如果使用本地缓存，可以加一个心跳进行处理。

现在的架构是比较信任cachecloud的高可用。
