### ISSUE TITLE
ERROR com.sohu.cache.machine.impl.MachineCenterImpl - SSH err: SSH authentication failed with [ userName: cachecloud, password: cachecloud]

### ISSUE THREAD

**Issue by wh211212** [sohutv/cachecloud#101]
![image](https://user-images.githubusercontent.com/16891171/30575059-b6e104ca-9d30-11e7-80bf-d0bb43e31fa4.png)

**Comment by lynguo** [comment]
在"系统配置管理中"ssh用户名和ssh密码应该写成你的redis所在电脑的用户名和密码

**Comment by zh15181387047** [comment]
请问问题解决了吗
