### ISSUE TITLE
ServerJob里面的代码为啥被注释了?

### ISSUE THREAD

**Issue by spccold** [sohutv/cachecloud#102]
如题
@carlosfu

**Comment by carlosfu** [comment]
@spccold 你好看下这个
https://cachecloud.github.io/2017/02/06/1.3.%E6%9C%BA%E5%99%A8%E7%9B%91%E6%8E%A7%E5%8A%9F%E8%83%BD/

**Comment by spccold** [comment]
ok! thank you.
