### ISSUE TITLE
redis集群扩容后应用怎样添加扩容后节点监控

### ISSUE THREAD

**Issue by minminmsn** [sohutv/cachecloud#103]
redis集群扩容后应用怎样添加扩容后节点监控   原来有6节点监控，现在扩容到8节点怎样监控。
另外业务下线后还能上线吗？没看到那里可以上线。

**Comment by geekyijun** [comment]
扩容功能在cc水平扩展中处理，会对新增节点自动加入监控。下线应用表示永久下线，会回收资源。不能再次上线。

**Comment by dinggel** [comment]
cc水平扩展 在哪里

**Comment by jedyang** [comment]
你的节点扩容是手动做的吧？cachecloud还没有扩容节点的功能吧？ @minminmsn 
同问 水平扩展在哪里？ @geekyijun

**Comment by jedyang** [comment]
我找到了，在申请扩容流程里

**Comment by dinggel** [comment]
@jedyang 申请扩容流程？？ 哪里呢
![image](https://user-images.githubusercontent.com/22829724/37394693-5244051c-27af-11e8-8601-42cb600b8f8d.png)

**Comment by dinggel** [comment]
@jedyang 原来是审批流程里 谢谢

**Comment by jedyang** [comment]
你水平扩展成功了吗？我这边实验报
java.lang.NumberFormatException: For input string: "6384@16384"
好奇@16384哪里来的？debug中。。。
@geekyijun @dinggel

**Comment by dinggel** [comment]
@jedyang 我和你一样的报错

**Comment by dinggel** [comment]
应该是jedis和redis版本的冲突

**Comment by jedyang** [comment]
@dinggel 我已经解决了，应该是版本问题。我改了下cachecloud的代码，
redis.clients.util.ClusterNodeInformationParser#getHostAndPortFromNodeLine
`return new HostAndPort(arrayHostAndPort[0].isEmpty() ? current.getHost() : arrayHostAndPort[0],
        arrayHostAndPort[1].isEmpty() ? current.getPort() : Integer.valueOf(arrayHostAndPort[1].split("@")[0]));`
就是对@做了下处理。测试成功的。
因为我们的cachecloud比较老了，之前就被自己人修改过，所以不清楚是否是cachecloud源码的问题。
供参考。

**Comment by minminmsn** [comment]
@jedyang 回头我试试，我节点扩容后一直没有找到怎样添加到原来的集群监控中，单独添加的一个新监控。
