### ISSUE TITLE
应用下线后怎样改成运行中状态

### ISSUE THREAD

**Issue by minminmsn** [sohutv/cachecloud#105]
大家好！
应用下线后怎样改成运行中状态，查看了所有的数据库表也没有看到修改的地方，UI上也没找到修改的地方？
![cc1](https://user-images.githubusercontent.com/17631009/31601356-2d7e9028-b28c-11e7-8e91-06739e839c3d.jpg)

**Comment by carlosfu** [comment]
@minminmsn 应用下线后改不回，所以请谨慎下线。
