### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by qw2283345** [sohutv/cachecloud#11]
花了一天的时间，部署了一下，已经能跑起来。不过有个小问题想问问， 生成redis是没有密码，也不绑定IP，请问你们是如何做安全验证这块的？

**Comment by carlosfu** [comment]
> 花了一天的时间，部署了一下，已经能跑起来。不过有个小问题想问问， 生成redis是没有密码，也不绑定IP，请问你们是如何做安全验证这块的？

主要是考虑到内网的环境，我们没有用密码，也没有bind ip，如果有需要可以添加密码，主要还是对内部比较信任。

当然flushall这类危险操作可以使用rename-command来完成。

对于外网的攻击：我们通过公司的防火墙完成、还有非root用户。

**Comment by qw2283345** [comment]
@carlosfu 嗯，看了一下源代码RedisConfigEnum这个枚举可以编辑配置信息，我建议还是可以自己设置密码，像我们这样都有这么好的内网条件。谢谢你的回答。也谢谢开源了一个这么好的项目，以你们为榜样

**Comment by qw2283345** [comment]
刚刚说错了，是像我们这样的都没有这么好的内网条件的，就需要考虑到这个安全验证的问题的了。

**Comment by carlosfu** [comment]
> 刚刚说错了，是像我们这样的都没有这么好的内网条件的，就需要考虑到这个安全验证的问题的了。

是的，你说的很对，我先mark一下，后期添加上。
