### ISSUE TITLE
主机监控是否需要额外配置？

### ISSUE THREAD

**Issue by sunnylou** [sohutv/cachecloud#112]
不做额外配置的情况下，主机监控没有数据，如图：
![default](https://user-images.githubusercontent.com/22695791/33014324-e91b1576-ce21-11e7-90b8-72b872ff34c0.png)
请问是否需要做额外的配置？

**Comment by carlosfu** [comment]
@sunnylou 参考下这个 https://cachecloud.github.io/2017/02/06/1.3.%E6%9C%BA%E5%99%A8%E7%9B%91%E6%8E%A7%E5%8A%9F%E8%83%BD/

**Comment by sunnylou** [comment]
昨天按这个配了,仍旧不太行，把注释去掉需要重新编译吗？
