### ISSUE TITLE
对cachecloud监控指标的建议

### ISSUE THREAD

**Issue by ghost** [sohutv/cachecloud#114]
搜狐的朋友，在刚刚使用过程中，发现cachecloud中缺少Expired与Evicted的统计，当使用redis作为非持久化缓存时，有时需要查看Expired与Evicted中未到期的key被踢出频率和踢出的量来决定是否在可接收范围，如果踢出过于频繁会考虑扩容集群使用量。

expired_keys:34562104
evicted_keys:1489068016

**Comment by carlosfu** [comment]
@youyang0414 在app_minute_statistics表中已经有分钟级别的expired_keys和evicted_keys。
