### ISSUE TITLE
是否支持redis4.0.2最新版本

### ISSUE THREAD

**Issue by shuohao** [sohutv/cachecloud#115]
是否支持redis4.0.2最新版本

**Comment by 18210792673** [comment]
兄弟，我测试过，可以支持单实例、哨兵、集群等的部署。但是集群扩容等功能无法支持（原因为Jedis客户端目前不支持4.0.2版本），所以目前还是建议使用3.2版本吧

**Comment by 18210792673** [comment]
可以加QQ群：534429768。一起讨论

**Comment by shuohao** [comment]
麻烦给通过一下 我申请加群了

**Comment by XMPST** [comment]
@watchmen1992 怎么我用redis3.2.11的版本，然后在后台部署不了redis集群的？

**Comment by chenshi6379** [comment]
可接入redis版本管理，支持不同redis版本的部署~
