### ISSUE TITLE
后续有没有计划开发支持cluster缩容

### ISSUE THREAD

**Issue by shuohao** [sohutv/cachecloud#118]
目前可以水平扩容，但是貌似没有收缩，有些场景可能会用到收缩腾出机器

**Comment by geekyijun** [comment]
好建议，我们会考虑，理论上跟水平扩容一样，都是slot到节点的迁移过程。

**Comment by fcfc20050545** [comment]
我看见源码中有预留的删除节点的接口，其实只要slot那部分单独拎出来，加上这个删除的就可以实现缩容了。关键是缩容后的节点数据库中的状态的处理，这个要考虑对之前系统的影响
