### ISSUE TITLE
请问redis cluster部署所在机器宕机后重启，只能在cachecloud下线该应用之后再重新部署吗？还是可以重启恢复

### ISSUE THREAD

**Issue by csspark** [sohutv/cachecloud#119]
请问redis cluster部署所在机器宕机后重启，只能在cachecloud下线该应用之后再重新部署吗？还是可以重启恢复

**Comment by geekyijun** [comment]
不需要，在后台运维界面有重启功能。
见:https://github.com/sohutv/cachecloud/wiki/2.%E8%BF%90%E7%BB%B4%E5%8A%9F%E8%83%BD#cc2

**Comment by csspark** [comment]
好的，谢谢
