### ISSUE TITLE
PHP怎么通过cachecloud连接到REDIS集群啊

### ISSUE THREAD

**Issue by starinskycc** [sohutv/cachecloud#120]

**Comment by geekyijun** [comment]
非java客户端需要使用RESTful api完成节点寻址初始化。见:https://github.com/sohutv/cachecloud/wiki/4.%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3#cc2-1
