### ISSUE TITLE
cache-cloud搭建的集群时如何做持久化的？

### ISSUE THREAD

**Issue by tianyangyang427** [sohutv/cachecloud#121]
之前使用redis cluster主从都开启bgsave持久化，发现并发量大的话，主节点会被阻塞；最后关闭主节点持久化功能，只在从节点开启持久化。问题得到解决，cachecloud在这方面是如何做的？

**Comment by geekyijun** [comment]
cachecloud默认采用AOF的everysec测试持久化，RDB相关的SAVE配置都关闭。
