### ISSUE TITLE
cachecloud.sql中的表machine_info缺少字段

### ISSUE THREAD

**Issue by showsean** [sohutv/cachecloud#122]
报错信息 

### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'collect' in 'field list'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'collect' in 'field list'] with root cause
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'collect' in 'field list'

**Comment by showsean** [comment]
找到问题了 使用mysql5.7  需要在my.cnf中配置 sql_mode=''

**Comment by geekyijun** [comment]
好的，cc没有在mysql5.7下测试。这个问题记下了，感谢。

**Comment by yfm10** [comment]
应该是machine_info没有collect字段吧

**Comment by turanorbob** [comment]
/**
     * 是否收集服务器信息，0否，1是
     */
    private int collect;

**Comment by turanorbob** [comment]
alter table machine_info add column `collect` default 0;

**Comment by dlhf** [comment]
缺少 collect 字段数据库
