### ISSUE TITLE
提一个功能建议

### ISSUE THREAD

**Issue by shuohao** [sohutv/cachecloud#124]
自动化部署的时候，比如部署主从哨兵，部署第一个实例127.0.0.1:6379检测后如果连不上报错，界面会提示部署失败，但是此时redis实例其实已经起来了，因为保护模式问题或者防火墙等原因没能连上实例。这就导致该实例已经没有用但却进程还在，后续可否考虑如果部署失败后自动删除已启动的实例进程以及配置文件数据文件等

**Comment by geekyijun** [comment]
好建议，我们会加入多节点操作的回滚功能。
