### ISSUE TITLE
申请应用，后台审批部署成功后，回到审批页面没有“通过”按钮

### ISSUE THREAD

**Issue by 945226956** [sohutv/cachecloud#127]
前端申请一个集群模式的应用，后台审批，部署成功后提示可以点击通过按钮，但是页面没有通过按钮，还是驳回和审批处理  两个按钮操作。

**Comment by wushun18** [comment]
遇到同样的问题

**Comment by 945226956** [comment]
你解决了嘛？

**Comment by wushun18** [comment]
并没有

**Comment by geekyijun** [comment]
没有通过提示 说明审批状态没有变更，看下后台日志有没有错误。

**Comment by wuisme** [comment]
额，我记得我遇到过这个问题，好像是因为那个初始化脚本，没有把Redis的相关路径加载到path里边。需要手工添加一下。

**Comment by jedyang** [comment]
这个原因很多，具体要看日志

**Comment by Leboudin** [comment]
刚刚解决了类似的问题，原因是阿里云没有配置安全组的端口，导致部署成功后 cachecloud 连接不到 redis，低级错误，供大家参考
