### ISSUE TITLE
在哨兵模式下,如何保持主/备实例的端口号一致?

### ISSUE THREAD

**Issue by lynch0227** [sohutv/cachecloud#130]
现在创建哨兵模式下的redis,应该是随机取当前主机最大端口号+1,可能会导致主/备端口号不一致.
在做failover时还需要修改端口号,不知道该如何解决这个问题?

**Comment by geekyijun** [comment]
cachecloud 对端口号分配按照固定原则，不允许手动分配，防止重用，避免cluster,sentinel服务重连到老的错误节点。
如果担心端口号记不住等问题，可以采用cachecloud的后台运维管理进行failover, up/down等操作。
也就是端口号是在CC上是一次性分配，一旦分配，在这台机器上新节点永不重用。
