### ISSUE TITLE
删除已驳回应用ID

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [sohutv/cachecloud#131]
![image](https://user-images.githubusercontent.com/26402190/36772469-6a8ead7c-1c90-11e8-9e7d-6ebe93cb2215.png)

**Comment by Blue-Skies-firststar** [comment]
这个显示在哪个表中，咋删除呢

**Comment by geekyijun** [comment]
cacheCloud的数据都是伪删除（下线状态），如果要彻底删除数据，设计多张表数据，不建议物理删除数据。
