### ISSUE TITLE
cachecloud部署成功后回到审核列表没有通过按钮

### ISSUE THREAD

**Issue by fanqixiong** [sohutv/cachecloud#133]
cachecloud所在的ip是192.168.12.226

192.168.12.226:1024:192.168.12.227
192.168.12.227:1024:192.168.12.226
192.168.12.226:1024:192.168.12.227
192.168.12.227:1024:192.168.12.226
192.168.12.226:1024:192.168.12.227
192.168.12.227:1024:192.168.12.226
192.168.12.226:1024:192.168.12.227
192.168.12.227:1024:192.168.12.226
192.168.12.226:1024:192.168.12.227
192.168.12.227:1024:192.168.12.226

![image](https://user-images.githubusercontent.com/25973767/38476065-815b7806-3bde-11e8-9afd-dca1e2637983.png)

![image](https://user-images.githubusercontent.com/25973767/38476130-bc7368a4-3bde-11e8-908e-099090625307.png)

**Comment by geekyijun** [comment]
这个提示只是提示格式正确，不是真正的部署。

**Comment by EonianGlutton** [comment]
看日志，肯定出错了

**Comment by ieayoio** [comment]
我也是，看日志只显示com.sohu.cache.redis.impl.RedisDeployCenterImpl - host:xx.xx.xx.xx;port:6385 not run

**Comment by ieayoio** [comment]
> 我也是，看日志只显示com.sohu.cache.redis.impl.RedisDeployCenterImpl - host:xx.xx.xx.xx;port:6385 not run

我的问题解决了，我用了新版的reids，在“Redis普通配置”里添加:
```
protected-mode no
bind 0.0.0.0
```
再次部署时间会比之前长一些，部署成功就会显示通过按钮
