### ISSUE TITLE
目前的版本CSS样式在生产环境无法加载的问题

### ISSUE THREAD

**Issue by dpheyu** [sohutv/cachecloud#134]
当前版本（截止到2018年4月），在生产环境部署后，部分页面加载样式时，无法加载成功，比如应用拓扑图中，就无法加载各个节点的角色对应的颜色等信息，因大部分公司生产环境都是内网，不会开通公网访问，无法访问到  http://www.bootcss.com/  这个地址，建议在下个版本的时候，把这些调用公网地址的地方能抽取出来，放在cachecloud自己的资源包里面。祝强大！！

**Comment by geekyijun** [comment]
好的，之后会做成本地静态资源。
