### ISSUE TITLE
数据库的一些问题和提醒，5.7版本mysql

### ISSUE THREAD

**Issue by fcfc20050545** [sohutv/cachecloud#137]
最近监控数据库报错，发现一些错误
AppClientCostTimeTotalStatDao.xml 下面 save 和 batchSave两个sql 在存在更新的语句中有一段mean = format(total_cost / total_count, 2)。format是字符串类型，三位用，隔开，赋值给mean double出错。
5.7版本提醒：
  本人用的5.7版本，有部分语法是group by select中存在不再group by中的字段，5.7后默认增加only_full_group_by模式，会报语法错误，修改sql 用 any_value包裹，或者改配置。建议写的语法符合sql规范。

**Comment by geekyijun** [comment]
收到issues，感谢。
