### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by marscqy** [sohutv/cachecloud#138]
errorMsg: ERR unknown command 'CONFIG'

我的集群中的redis的config重命名过，应该有个地方可以配置这个config。
并且失败之后会一直重试，反复打日志，这个比较危险。

顺便提个书中的错误吧。P161，Redis持久化文件加载流程，我反复看了redis的源码，并且试验，开了开了AOF，但是没AOF文件，但是又RDB文件，这时候数据库是不加载数据的。

书是早就看了，还有几处忘记了，对这个持久化的印象比较深。

**Comment by geekyijun** [comment]
感谢帮助纠错，错误已经修改了，在下一印刷会纠正。
命令重命名可以使用rename-command配置设置。

**Comment by marscqy** [comment]
重命名已经设置了，但是cachecloud里面没有相关的配置，我只能修改cachecloud的代码进行部署，代码里面用enum来包装redis的命令，但是很多命令在正式环境中是要重命名过的，所以会报错，这个是改进的一个点吧。
https://github.com/marscqy/cachecloud/tree/master/docker这里我提供了docker化，方便部署。

**Comment by marscqy** [comment]
https://github.com/marscqy/redis-in-k8s  这是我的一个k8s部署redis集群的项目，其中遇到了一些问题。
比如集群自动扩容。
自动扩容是这样的，redis集群扩容分为2步，第一步新节点加入集群，第二步，slot迁移，问题出在slot迁移，如果slot迁移的时候，这个slot有数据，迁移就会失败，需要等待第一步操作完成之后一段时间才能开始迁移slot，这个等待一段时间不好确定，不知道你们有没有相关的运维经验。
