### ISSUE TITLE
cachecloud支持redis cluster的自动水平扩容吗

### ISSUE THREAD

**Issue by DEATHGUN3** [sohutv/cachecloud#142]
比如我原来有6节点监控，现在我只想在cachecloud-web上添加一下扩容的节点信息，比如点某个按钮后cachecloud会自动帮我扩容到8节点监控，请问有这样的功能吗？

**Comment by fcfc20050545** [comment]
目前只可以，客户端申请后有个选项进行水平扩容。后台好像不可以主动发起，水平扩容也存在问题，下线后的实例会导致失败，我最近也在修改这段的相关内容，不知道是不是系统的bug。你可以尝试把那段水平扩容单独改造一下，具体实现的代码，原来项目已经存在。

**Comment by DEATHGUN3** [comment]
@fcfc20050545 ok，我了解了，我说的是cachecloud水平扩容的具体方式，非常感谢你详细的答复！

**Comment by snailshen2014** [comment]
控制台是不支持的，我的想法是用后台命令进行扩容，但是不知道控制台能不能看到扩容后的节点，这个还没有测试

**Comment by chenshi6379** [comment]
推荐采取应用迁移的方式，如果使用水平扩容的话，当分片内存较大的时候，时间会较长 而且迁移期间出问题 不容易解决。
