### ISSUE TITLE
cachecloud开启机器监控功能，还有哪些注意点

### ISSUE THREAD

**Issue by DEATHGUN3** [sohutv/cachecloud#143]
我按照官方文档[https://cachecloud.github.io/2017/02/06/1.3.%E6%9C%BA%E5%99%A8%E7%9B%91%E6%8E%A7%E5%8A%9F%E8%83%BD/](url)，注释掉了相关代码，也将cachecloud-open-web/nmon放到和cachecloud部署的同级目录，machine_info表中的collect也设置为1。但是启动之后一直报下面这个错：
![collect](https://user-images.githubusercontent.com/30991433/41897294-85e35c82-7959-11e8-9127-512276f27960.png)，请问还有哪些地方需要注意的吗？

**Comment by githubname1024** [comment]
需要将nmon服务包，命名为nmon，并拷贝到/opt/cachecloud/soft文件夹下即可。不需建立nmon文件夹。
