### ISSUE TITLE
RedisSentinelBuilder类中Lock使用方式 有误！

### ISSUE THREAD

**Issue by suifeng3051** [sohutv/cachecloud#144]
LOCK.tryLock(10, TimeUnit.MILLISECONDS);
上面这句有可能获取不到 锁，而后面又调用了LOCK.unlock()方法，并发情况下会抛出java.lang.IllegalMonitorStateException异常。

**Comment by suifeng3051** [comment]
@carlosfu 看一下这个问题吧

**Comment by snailshen2014** [comment]
是的，我已经修复了
