### ISSUE TITLE
cachecloud新版本什么时候发布呢？

### ISSUE THREAD

**Issue by dpheyu** [sohutv/cachecloud#148]
作者你好，请问什么时候发布新的版本，新的版本是否支持redis4.0呢？因为当前版本对密码支持较弱，而考虑到安全性，生产实践时，必须设置密码。

**Comment by cnodin** [comment]
这个基本上没人维护了吧，快一年没有commit了。可惜了。

**Comment by carlosfu** [comment]
@cnodin 维护的。

**Comment by cnodin** [comment]
赞，很好的项目。会考虑升级下spring boot和redis的支持版本么

**Comment by carlosfu** [comment]
@cnodin 会的。

**Comment by cghtom** [comment]
作者你好，请问什么时候发布新的版本? 同上问

**Comment by chenshi6379** [comment]
已发布了2.0版本 [Changelog](https://github.com/sohutv/cachecloud/releases/tag/2.0)，欢迎试用
