### ISSUE TITLE
希望能在UI界面上添加现有的redis cluster信息

### ISSUE THREAD

**Issue by liushifa** [sohutv/cachecloud#15]
希望能在UI界面上添加现有的redis cluster信息，且有可能是不同版本，不同安装位置

**Comment by carlosfu** [comment]
> 希望能在UI界面上添加现有的redis cluster信息，且有可能是不同版本，不同安装位置

这个现在cachecloud还是不支持，cachecloud现在采用统一的ssh用户，统一的目录。

如果有需要可以支持更加灵活的配置，方便接入稍前的redis信息

**Comment by carlosfu** [comment]
@liushifa 

> 希望能在UI界面上添加现有的redis cluster信息，且有可能是不同

这个问题已经修复，详见：http://cachecloud.github.io/2016/04/17/%E5%B7%B2%E5%AD%98%E5%9C%A8Redis%E6%8E%A5%E5%85%A5CacheCloud/
