### ISSUE TITLE
邮件和短信报警的http接口规范啥时候能支持？

### ISSUE THREAD

**Issue by ccall248** [sohutv/cachecloud#150]
之前已经用到生产环境，因java不熟悉，一直无法实现邮件和短信告警，总感觉效果大打折扣，无法做到真正的自动化。期待大神能尽快发布邮件和短信报警的http接口规范，这样就可以用python实现之了。

**Comment by snowkity2005** [comment]
请问邮件和短信报警的http接口规范现在发布了吗？

**Comment by chenshi6379** [comment]
现在新版本支持 微信、邮件 HTTP接口,可以在CacheCloud后台 系统配置 里面做配置~
