### ISSUE TITLE
ERROR com.sohu.cache.async.impl.AsyncServiceImpl - machine-pool is assembled 

### ISSUE THREAD

**Issue by chouchou900822** [sohutv/cachecloud#153]
ERROR com.sohu.cache.async.impl.AsyncServiceImpl - machine-pool is assembled
因为这个错误 docker的supervisor一直起不起来
如何消除这个错误

**Comment by zhzpython** [comment]
请问解决了吗，我也是这个问题

**Comment by vosamo** [comment]
@chouchou900822 请问这个问题咋解决的？

**Comment by githubname1024** [comment]
经确认，项目启动时，会调用两次将machine-pool放入Map中，而map的key即为machine-pool，导致第二次放入时，失败。此报错并不影响系统正常运行，可忽略。如系统不能正常运行，请排查其他错误。目前main分支已将该日志保持级别更正为warn。
