### ISSUE TITLE
这个文件是乱码

### ISSUE THREAD

**Issue by wangxulong511** [sohutv/cachecloud#158]
https://github.com/sohutv/cachecloud/blob/12123e718dd18373d08cecaca961648927deefbd/cachecloud-open-web/src/main/webapp/WEB-INF/resources/widgets/jscalendar/lang/calendar-hr.js#L21

**Comment by shaohuanan** [comment]
请问这个问题解决了吗

**Comment by chenshi6379** [comment]
这个只是js文件的编码问题把~
