### ISSUE TITLE
在机器管理中添加机器提这个错误

### ISSUE THREAD

**Issue by R1hug0** [sohutv/cachecloud#16]

**Comment by carlosfu** [comment]
> Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'modify_time' cannot be null

请更新代码，之前我们已经修复了这个问题，应该是mysql版本造成的，我们已经从代码层面兼容了。

**Comment by carlosfu** [comment]
#5
