### ISSUE TITLE
maven构建项目的时候web目录报错

### ISSUE THREAD

**Issue by ly1990** [sohutv/cachecloud#161]
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-remote-shell</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>

[ERROR] Failed to execute goal on project cachecloud-open-web: Could not resolv
 dependencies for project com.sohu.tv:cachecloud-open-web:war:1.0-SNAPSHOT: Fai
ed to collect dependencies at org.springframework.boot:spring-boot-starter-remo
e-shell:jar:1.3.1.RELEASE: Failed to read artifact descriptor for org.springfra
ework.boot:spring-boot-starter-remote-shell:jar:1.3.1.RELEASE: Could not transf
r artifact org.springframework.boot:spring-boot-starter-remote-shell:pom:1.3.1.
ELEASE from/to com.springsource.repository.maven.release (http://repo.springsou
ce.org/release/): Connect to repo.springsource.org:80 [repo.springsource.org/35
241.58.96] failed: Connection timed out: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swi
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please re
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyRes
lutionException

**Comment by carlosfu** [comment]
加-e 看看什么错误

**Comment by myysophia** [comment]
用阿里雲的maven setting 就好了:)
