### ISSUE TITLE
客户端上报异常

### ISSUE THREAD

**Issue by LeeGuoPing** [sohutv/cachecloud#165]
现在的cachecloud中默认启动的一个每天12点执行的定时任务删除收集的客户端数据上报数据, 但是我们没有使用经过包装的jedis来收集客户端的上报数据. 此时会出现这个异常. 建议查询总数做一下校验. 或者此处使用包装类型Long. mapper.xml中也改成Long. 这样就允许返回值为null. 可以根据null 做判断.

![image](https://user-images.githubusercontent.com/35389145/46127231-a247d400-c262-11e8-81fa-d0c3b1464e58.png)

**Comment by LeeGuoPing** [comment]
这是我修改的地方.
![image](https://user-images.githubusercontent.com/35389145/46127617-cf48b680-c263-11e8-8317-4550b04a416b.png)

**Comment by geekyijun** [comment]
感谢提醒。
