### ISSUE TITLE
redis security建议

### ISSUE THREAD

**Issue by krast** [sohutv/cachecloud#170]
### 基本信息

- cachecloud 版本：1.0
- cachecloud环境：centos7
- jdk版本: openjdk1.8
- redis版本: 4.0

### 需求及现象描述
[官方redis security](https://redis.io/topics/security)
目前我的需求是默认redis-cli命令disable
以及各类安全加固的配置项
手动启动redis配置文件中加入：
```
rename-command KEYS ""
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
```
因为instance_config表中的config_key是unique
所以多行rename-command无法通过cachecloud配置管理模版写入
![image](https://user-images.githubusercontent.com/2233563/49788195-a82e5b00-fd63-11e8-8aa3-e33a1b11be1f.png)

### 临时解决方案
修改com.sohu.cache.redis.enums.RedisConfigEnum
加入rename-command相关配置
修改com.sohu.cache.redis.impl.RedisConfigTemplateServiceImpl
handleCommonConfig方法加入安全加固配置
效果：
![image](https://user-images.githubusercontent.com/2233563/49788888-803ff700-fd65-11e8-8933-dc036bdb3bc0.png)

### 个人建议
个人想法是加入安全加固的配置模版，加入security模版类型，同standalone、cluster、sentinel为第四类型的配置模版。加入常用的安全加固配置项

**Comment by geekyijun** [comment]
好建议，我们会采纳。
