### ISSUE TITLE
cachecloud

### ISSUE THREAD

**Issue by zzzxx** [sohutv/cachecloud#174]
现在项目还在维护吗？

**Comment by carlosfu** [comment]
@zzzxx 还在维护，今年会发一个大版本。

**Comment by lamoce** [comment]
@carlosfu 大概有发布的时间计划吗？

**Comment by chenshi6379** [comment]
已经发布了2.0版本 [Changelog](https://github.com/sohutv/cachecloud/releases/tag/2.0)
