### ISSUE TITLE
jdbc.properties中的配置不生效

### ISSUE THREAD

**Issue by Mshuyan** [sohutv/cachecloud#176]
cachecloud使用过程中出现因为mysql版本导致的异常，下载源码对sql修改后编译并启动，但是程序始终没有加载jdbc.properties中的配置，而是使用的online.properties中的配置，请教关于加载jdbc.properties中配置部分的代码在哪里

**Comment by zouzc** [comment]
同求配置在哪儿生效的。

**Comment by chenshi6379** [comment]
这个需要在项目编译 通过mvn 指定profile环境吧 ~
