### ISSUE TITLE
后台管理页面乱码

### ISSUE THREAD

**Issue by gaoyuke** [sohutv/cachecloud#179]
![image](https://user-images.githubusercontent.com/31268133/54415967-ebb8ac80-4738-11e9-975e-7b331d495b8d.png)
应用详情和审批列表下的乱码

**Comment by carlosfu** [comment]
@gaoyuke 看下问题1  https://cachecloud.github.io/2016/04/12/CacheCloud%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/
