### ISSUE TITLE
问一下，我的redis集群有密码应该用哪个版本啊

### ISSUE THREAD

**Issue by zzzxx** [sohutv/cachecloud#183]
问一下，我的redis集群有密码应该用哪个版本啊

**Comment by dishytianxiang** [comment]
我试了下，1.2完全不支持密码，现在的master分支只支持部署第一步输入密码，扩展节点不支持密码，所以水平扩容不行，不知道这个4.3k的star怎么来的，master拉下来代码，界面显示部署的有个单独的密码项，要不是临时加的，要不代码就不更新上来，我被坑了2天了。。。。

**Comment by liusl104** [comment]
+1

**Comment by chenshi6379** [comment]
可以使用 cachecloud迁移工具 把源集群数据导入到cachecloud应用中。
