### ISSUE TITLE
难道该项目已死？

### ISSUE THREAD

**Issue by adminops** [sohutv/cachecloud#196]
看来这个开源项目已死，体验优化、功能增加、redis支持4.x、5.x很多都没有做，代码已经很久没提交了。

**Comment by krast** [comment]
redis支持4.x，我现在想要重新用vue做一套，底层代码也要改改了，有兴趣的可以私

**Comment by liu316484231** [comment]
请问项目开发者还有几个还在搜狐的。。

**Comment by wayne1128** [comment]
------------------ 原始邮件 ------------------
发件人: "pmwx9"<notifications@github.com>;
发送时间: 2019年9月18日(星期三) 下午4:01
收件人: "sohutv/cachecloud"<cachecloud@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [sohutv/cachecloud] 难道该项目已死？ (#196)




请问项目开发者还有几个还在搜狐的。。

**Comment by it-noob** [comment]
之前问过作者说，会有一个 springboot 版本发出来，但是后来没什么信息了

**Comment by chenshi6379** [comment]
已经发布了2.0新版本 [changelog](https://github.com/sohutv/cachecloud/releases/tag/2.0)
