### ISSUE TITLE
高可用

### ISSUE THREAD

**Issue by oldshipmaster** [sohutv/cachecloud#2]
这个redis的高可用，主要是依赖于redis的sentinel，和cluster？如果是主从部署，不支持高可用？

**Comment by oldshipmaster** [comment]
还有一个问题是，提供给业务方的方式啥，比如我申请了20个redis实例，那么我要配20个hostport？在单机的情况下，这种实例链接的配置信息，是暴露给业务方自己配的？如果有redis挂了，那么需要重启业务？

**Comment by oldshipmaster** [comment]
还有一个问题是，贵公司引入的jedis的代码到项目中，是对jedis代码做了修改么？

**Comment by oldshipmaster** [comment]
看到源码中，通过appid去连接，redis实例，发一个http请求只推一次hostport，如果中途这个机器挂了，那么就会导致业务方不能连接这个redis，需要运维手动接入么？

**Comment by carlosfu** [comment]
@oldshipmaster 

> 这个redis的高可用，主要是依赖于redis的sentinel，和cluster？如果是主从部署，不支持高可用？

cachecloud支持redis-sentinel redis-cluster 和 redis主从结构三种结构，都是官方的高可用实现方案。

**Comment by carlosfu** [comment]
> 还有一个问题是，提供给业务方的方式啥，比如我申请了20个redis实例，那么我要配20个hostport？在单机的情况下，这种实例链接的配置信息，是暴露给业务方自己配的？如果有redis挂了，那么需要重启业务？



> 看到源码中，通过appid去连接，redis实例，发一个http请求只推一次hostport，如果中途这个机器挂了，那么就会导致业务方不能连接这个redis，需要运维手动接入么？

只有在应用端启动的时候会调用一次http拿到Redis的相关分片信息，之后完全依赖于jedis实现高可用和故障转移。
我们的cachecloud是高可用的，一般不会出现问题。不过这个之后可以改进一下，可以在客户端加入本地缓存。

**Comment by carlosfu** [comment]
> 还有一个问题是，贵公司引入的jedis的代码到项目中，是对jedis代码做了修改么？

基本没有修改，和jedis官方基本一致，只是添加了客户端统计功能和部分redis cluster的批量操作封装

**Comment by carlosfu** [comment]
> 还有一个问题是，提供给业务方的方式啥，比如我申请了20个redis实例，那么我要配20个hostport？在单机的情况下，这种实例链接的配置信息，是暴露给业务方自己配的？如果有redis挂了，那么需要重启业务？

给应用方是一个appid加一个客户端，如果不是java语言，有一个restAPI。
Redis中途挂掉，完全依赖于像jedis这样客户端是否做到智能。

**Comment by carlosfu** [comment]
@oldshipmaster  目前我们cachecloud已经运行1年半了，非常稳定，但是现在还没有往外推广，欢迎使用。

**Comment by carlosfu** [comment]
@oldshipmaster  有一个简单的接入视频 http://my.tv.sohu.com/pl/9100280/index.shtml 可以参考一下
