### ISSUE TITLE
默认配置不支持mysql8

### ISSUE THREAD

**Issue by ariallyp** [sohutv/cachecloud#201]
用mysql8.0配置的时候，发现会报错，改成mysql5.6后，启动正常。

**Comment by 631086083** [comment]
mysql5.8之后的版本，数据库需要设置ssl和时区等等，url需要修改下，可以自行百度配置一下

**Comment by ariallyp** [comment]
原来如此，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "631086083"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 下午5:27
收件人: "sohutv/cachecloud"<cachecloud@noreply.github.com&gt;; 
抄送: "【清風颯颯】"<arial@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sohutv/cachecloud] 默认配置不支持mysql8 (#201)




mysql5.8之后的版本，数据库需要设置ssl和时区等等，url需要修改下，可以自行百度配置一下

**Comment by daviddai1998** [comment]
> mysql5.8之后的版本，数据库需要设置ssl和时区等等，url需要修改下，可以自行百度配置一下

您好，可以详细说下怎么解决吗，没有太明白如何修改url。如果能把百度链接告诉我就最好了，感激不尽。

**Comment by chenshi6379** [comment]
2.0版本的 sql.driver 已经升级到8.0.16 ，时区问题也已经做了兼容~
