### ISSUE TITLE
克隆项目到本地编译jdbc.driver的占位符未被替换

### ISSUE THREAD

**Issue by Liuxboy** [sohutv/cachecloud#203]
1、克隆项目到本地
2、到项目根目录下，执行mvn clean compile install -Plocal
3、生成的target/classes/spring/spring-mybatis.xml的driverClass与preferredTestQuery对应的value${}未被替换，而导致期启动时mysql的Driver相关的Bean加载不了。但是其它配置项都替换了，很诡异。
![image](https://user-images.githubusercontent.com/3283061/71317704-5cf37000-24c0-11ea-8b5c-ceb818bfa876.png)

maven版本是3.3.9
JDK是1.8.0_45
使用IDEA编译同样是这个问题，在application.properties文件中，CTRL+jdbc.driver，是能跳到spring-mybatis.xml中对应项的

**Comment by chenshi6379** [comment]
可以参考下系统接入文档 [quick start](https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/static/wiki/quickstart/index.md)
