### ISSUE TITLE
修改cachecloud根目录

### ISSUE THREAD

**Issue by pan724** [sohutv/cachecloud#208]
请问怎么修改cacheclod默认要目录，例如我打算将redis相关信息放在/data，申请一个应用后，数据和日志目录结构：/data/redis/应用名/{data,log,conf},redis软件目录：/data/app/redis，因为我们会在一台机器上部署多个redis，按默认根目录部署的话，文件组织有点乱，盼回复，多谢

**Comment by chenshi6379** [comment]
Redis机器默认初始化目录是这个结构：
日志目录：/opt/cachecloud/logs/
持久化目录：/opt/cachecloud/data/
配置文件目录：/opt/cachecloud/conf/
如果是部署多个实例 也不会影响，每个实例的日志、持久化、配置文件都会端口区分开，不会影响。
