### ISSUE TITLE
注册请新用户时若有重复时不提示

### ISSUE THREAD

**Issue by R1hug0** [sohutv/cachecloud#21]
后台前台均无任何提示，唯有看日志，能在新用户申请的时候判断一下不

**Comment by carlosfu** [comment]
@R1hug0 

非常感谢提醒，现在已经在前台通过ajax到后台验证，后台逻辑没有变，考虑到内网的安全，没有处理恶意访问。

请更新代码！

<img src="http://i3.itc.cn/20160321/3084_4e2f80b2_e75b_3c44_609d_d99b30394125_1.png"/>
