### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by louis-wonder** [sohutv/cachecloud#216]
执行命令：mvn clean compile install -Ponline 时报错
[ERROR] Failed to execute goal on project cachecloud-open-client-basic: Could not resolve dependencies for project com.sohu.tv:cachecloud-open-client-basic:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.slf4j:slf4j-api:jar:1.7.6: Failed to read artifact descriptor for org.slf4j:slf4j-api:jar:1.7.6: Could not transfer artifact org.slf4j:slf4j-api:pom:1.7.6 from/to central (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]

解决办法：
需要进行repo 的https 的修改(/root/.m2/目录下的相关文件和cachecloud 下的文件) 

报错2：No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
解决办法：
yum install java-devel

<mark 一下>

**Comment by chenshi6379** [comment]
可以参考下接入文档 [quick start](https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/static/wiki/quickstart/index.md)
