### ISSUE TITLE
关于内存使用率计算方式的问题

### ISSUE THREAD

**Issue by zackzhangCN** [sohutv/cachecloud#217]
以cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appStat.jsp为例, 内存使用率为什么不使用 usedMemory/maxMemory去计算呢? 

实际使用过程中遇到了这个问题, 现有的maxMemory * memoryUsedPercent / maxMemory计算结果与实际占用率不符的情况.

**Comment by chenshi6379** [comment]
可以去看下源码，内存使用率是这样计算的： double percent = 100 * (double) usedMemory / (maxMemory);
