### ISSUE TITLE
cachecloud有python API吗？

### ISSUE THREAD

**Issue by buhuaqi** [sohutv/cachecloud#218]
cachecloud有python接入的API吗？

**Comment by geekyijun** [comment]
非java语言环境可以通过RESTFul api获取节点信息，进行初始化。

**Comment by geekyijun** [comment]
https://github.com/sohutv/cachecloud/wiki/4.%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3#cc2-1

**Comment by buhuaqi** [comment]
> https://github.com/sohutv/cachecloud/wiki/4.%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3#cc2-1

收到，十分感谢
