### ISSUE TITLE
pom.xml中maven仓库应改为https连接

### ISSUE THREAD

**Issue by daviddai1998** [sohutv/cachecloud#219]
原来http中有些依赖无法下载
Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.

If you're receiving this error, then you need to replace all URL references to Maven Central with their canonical HTTPS counterparts:

Replace http://repo1.maven.org/maven2/ with https://repo1.maven.org/maven2/

Replace http://repo.maven.apache.org/maven2/ with https://repo.maven.apache.org/maven2/

**Comment by geekyijun** [comment]
done
