### ISSUE TITLE
cachecloud-init.sh执行出现chwon: 无效的组: "cachecloud-open:zc123123" 是否算成功

### ISSUE THREAD

**Issue by zczhangchun** [sohutv/cachecloud#225]
之前执行过一次该cachecloud-init.sh脚本，但是好像没成功，具体的结果也没有截图下来。
然后在次运行cachecloud-init.sh脚本出现下面的情况，是成功了吗。
![image](https://user-images.githubusercontent.com/42573478/100407896-98b99100-30a4-11eb-970f-a0e4d2254648.png)

**Comment by githubname1024** [comment]
Since this issue is about two years ago. And I can't make sure the version of the cachecloud-init.sh，so I just close this issue. If there is any future information, it is OK with reopen.
