### ISSUE TITLE
普通用户登陆问题。

### ISSUE THREAD

**Issue by HibikiLinux** [sohutv/cachecloud#228]
1.请问cachecloud提供的LDAP接入接口在哪里配置？
2.普通用户（非管理员）如何才能设置密码登陆。

**Comment by cassie-cao** [comment]
1.CacheCloud2.0中已经移除LDAP接入接口；
2.普通用户点击“新用户注册”，提交用户申请，管理员通过后方可访问（初始密码同用户名）。
