### ISSUE TITLE
服务器部署执行/etc/init.d/cachecloud-web start 无法成功启动 提示“syntax error near unexpected token”

### ISSUE THREAD

**Issue by shaozhengmao** [sohutv/cachecloud#23]
系统CentOS-5.3-i386 32位

问题提示：

[root@localhost opt]# /etc/init.d/cachecloud-web start 

/etc/init.d/cachecloud-web: line 168: syntax error near unexpected token `>'

/etc/init.d/cachecloud-web: line 168: `    $command &>> "$log_file" &'

**Comment by AirJay** [comment]
相同问题，cachecloud-web.conf文件是否需要根据环境做相应修改？

**Comment by carlosfu** [comment]
@shaozhengmao @AirJay 

应该是操作系统原因，我们用的是redhat，这个问题我们会尽快跟进处理。

**Comment by carlosfu** [comment]
@shaozhengmao @AirJay 

问题已经修复，请更新代码！

cachecloud根目录下的script目录下start.sh和stop.sh放在/opt/cachecloud-web执行就是开启和关闭cachecloud。
