### ISSUE TITLE
Sentinel和Cluster同IP部署显示错误，无法部署

### ISSUE THREAD

**Issue by useager** [sohutv/cachecloud#230]
![image](https://user-images.githubusercontent.com/64818588/104846649-875b6b00-5916-11eb-9afe-ae6aad3ca64a.png)
Sen'tin'el和Cluster的主从节点IP如果相同会报错，如上

**Comment by cassie-cao** [comment]
主从节点不能部署在一台机器上，否则这台机器挂掉，无法实现故障转移。
