### ISSUE TITLE
这次版本为啥要依赖redis  有没有文档说明  代码更新了文档没更新

### ISSUE THREAD

**Issue by heng1234** [sohutv/cachecloud#231]
这次版本为啥要依赖redis  有没有文档说明  代码更新了文档没更新

**Comment by chenshi6379** [comment]
这个依赖不是强依赖，主要是存放 cachecloud系统任务流日志以及 应用诊断任务的中间结果 。在启动完cachecloud 可以开通一个应用，配置好就可以。 之后我们梳理一个文档 可供你们配置参考。

**Comment by heng1234** [comment]
我发现这次版本不能在一台机器同时添加redis和sentinel  只能分开  测试环境没那么多机器的怎么处理呢



xiaoluoheng@foxmail.com
 
发件人： chenshi
发送时间： 2021-01-18 10:53
收件人： sohutv/cachecloud
抄送： hlvy; Author
主题： Re: [sohutv/cachecloud] 这次版本为啥要依赖redis 有没有文档说明 代码更新了文档没更新 (#231)
这个依赖不是强依赖，主要是存放 cachecloud系统任务流日志以及 应用诊断任务的中间结果 。在启动完cachecloud 可以开通一个应用，配置好就可以。 之后我们梳理一个文档 可供你们配置参考。

**Comment by githubname1024** [comment]
1. 依赖redis的原因，项目中有部分业务在执行时，需要保持最终结果或执行过程结果，但又不需要永久保存，目前是选择存储在redis中。可根据自身情况修正。
2. 目前为了保证可用性，sentinel和redis是不支持部署再同一个机器上的。可自行修改代码中的限制。仅需修改appDeployDetail.jsp中sentinel机器select框选部分代码即可。
