### ISSUE TITLE
导入应用输入了redis密码,但是app_desc的password字段还是空的,通过界面修改redis密码提示修改成功,后台查询表还是空的

### ISSUE THREAD

**Issue by zxb2503** [sohutv/cachecloud#236]
![image](https://user-images.githubusercontent.com/76046810/105828914-a89b1600-5ffe-11eb-9bfb-5afe6443c53c.png)
![image](https://user-images.githubusercontent.com/76046810/105828951-b81a5f00-5ffe-11eb-86f9-4d9073ac2395.png)
![image](https://user-images.githubusercontent.com/76046810/105828985-c2d4f400-5ffe-11eb-9f7d-1575ba731e3e.png)
![image](https://user-images.githubusercontent.com/76046810/105829017-cbc5c580-5ffe-11eb-9400-e390de2440c2.png)
![image](https://user-images.githubusercontent.com/76046810/105829071-dbdda500-5ffe-11eb-99af-47fc1bda8331.png)

**Comment by githubname1024** [comment]
可查看main分支，当前已支持修改密码且支持自定义密码。且已修复之前版本修改密码某些情况下失败的bug。[49fc011](https://github.com/sohutv/cachecloud/commit/49fc011c2119be489b8c97b78f36ee56aa5b1691) [ceb62df](https://github.com/sohutv/cachecloud/commit/ceb62df96cc7f1b075b5a26a9cd8bdbf4ea0f15a)
