### ISSUE TITLE
BUG: “机房名称”功能存在bug

### ISSUE THREAD

**Issue by Joncer** [sohutv/cachecloud#237]
修改机房信息的表单中，“机房名称”可能和修改个人资料的“域账户名”重复，导致“机房名称”变成“域账户名”。
![image](https://user-images.githubusercontent.com/5344551/107509797-01ada100-6bde-11eb-96a1-cf440f030669.png)

**Comment by githubname1024** [comment]
Thanks for pointing out this bug. We have fixed in main branch. [aee94ba](https://github.com/sohutv/cachecloud/commit/aee94baa275378da1379e9d8fc8c17b2db035edc)
