### ISSUE TITLE
redis版本升级

### ISSUE THREAD

**Issue by sandyao** [sohutv/cachecloud#246]
wiki中升级redis版本的操作文档为空，请帮忙提供，我这现需求想升级5.0.12。谢谢。
目录
一、目的
二、新增版本及配置
2.1 新增版本
2.2 新增配置
2.3 申请应用
三、应用版本升级

**Comment by chenshi6379** [comment]
首先需要把5.0.12加入版本管理 ，
1).如果是5.0.x小版本升级的话 ： 在应用运维 可以做小版本升级；
2).如果是3.0.x/4.0.x 大版本升级 ，需要做应用迁移 ，升级步骤参考文档：https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/static/wiki/operate/appUpgrade.md

**Comment by githubname1024** [comment]
收到反馈，将在main分支进行wiki更新。
如果升级版本跨度较大，建议新建redis服务，进行数据迁移后，用新服务替换掉老版本服务。如果只是小版本的升级，如5.0.9升级到5.0.12，在确保5.0.12已配置到cachecloud系统后，则可执行应用运维中，版本升级即可。
