### ISSUE TITLE
cachecloud-web.war 路径丢失

### ISSUE THREAD

**Issue by sandyao** [sohutv/cachecloud#247]
嗨，http://47.97.112.178/redis-ecs/ 路径丢失，请处理一下提供2.1版本的war包，十分感谢。

**Comment by chenshi6379** [comment]
ecs机器地址变更过 ，从这里下载： https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/static/wiki/quickstart/index.md
