### ISSUE TITLE
本地启动后，发现登录页面打不开

### ISSUE THREAD

**Issue by lakeylin** [sohutv/cachecloud#248]
网页提示以下错误：

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon May 31 23:24:16 CST 2021
There was an unexpected error (type=Not Found, status=404).
JSP file [/WEB-INF/jsp/manage/login.jsp] not found

**Comment by Terrynech** [comment]
同问, 请问你解决了吗?

**Comment by Terrynech** [comment]
> 网页提示以下错误：
> 
> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Mon May 31 23:24:16 CST 2021
> There was an unexpected error (type=Not Found, status=404).
> JSP file [/WEB-INF/jsp/manage/login.jsp] not found
同问, 请问你解决了吗?

**Comment by githubname1024** [comment]
如果为idea本地启动，请在启动配置中配置Working directory: $MODULE_WORKING_DIR$，试一下。
