### ISSUE TITLE
在后台“机器管理”中无法删除没有连接成功的host

### ISSUE THREAD

**Issue by renhongchang** [sohutv/cachecloud#25]
在后台“机器管理”中添加了一台机器，此机器优于其他原因无法正常连接，于是需要删除，但此时点击删除无效果，无法正常删除

**Comment by sohutv** [comment]
> 在后台“机器管理”中添加了一台机器，此机器优于其他原因无法正常连接，于是需要删除，但此时点击删除无效果，无法正常删除

已经修复，参数传递问题造成，请更新代码

**Comment by carlosfu** [comment]
已经修复，参数传递问题造成，请更新代码
