### ISSUE TITLE
为什么添加主机一直是收集状态

### ISSUE THREAD

**Issue by hydgladiator** [sohutv/cachecloud#252]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/13326206/122897717-d5b8de00-d37c-11eb-8b27-25635a223601.png">
我是WAR包部署在192.168.3.119上。
分别添加了3.119 / 3.220 / 3.223 三台虚拟机IP，同时也配置了宿主机IP。
但是主机添加完后，一直处于“收集中”状态

**Comment by macaty** [comment]
帐号密码不对，检查一下防火墙设置

**Comment by githubname1024** [comment]
请查看cachecloud后台系统中配置的机器ssh用户名和密码，并确认是否有在机器中配置该账号。
