### ISSUE TITLE
清理任务中有一个sql没有的表app_client_costtime_minute_stat_total

### ISSUE THREAD

**Issue by shuishui3** [sohutv/cachecloud#253]
cachecloud/cachecloud-web/src/main/java/com/sohu/cache/schedule/jobs/CleanupDayDimensionalityJob.java /
清理任务中有一个cachecloud/cachecloud-web/sql/2.0.sql没有的表app_client_costtime_minute_stat_total

**Comment by githubname1024** [comment]
此表已废弃，可删除相关代码，或查看最新main分支。
