### ISSUE TITLE
AppDao.xml#getAllAppDescList 存在SQL注入

### ISSUE THREAD

**Issue by haby0** [sohutv/cachecloud#261]
在AppController类的doAppList方法中，用户接收[appParam](https://github.com/sohutv/cachecloud/blob/2973a55cbd11ca1b7ca36226846dbaaad67e2d8d/cachecloud-web/src/main/java/com/sohu/cache/web/controller/AppController.java#L852)变量值做为appName赋值给AppSearch实例对象,然后AppServiceImpl类的[getAppDescList](https://github.com/sohutv/cachecloud/blob/2973a55cbd11ca1b7ca36226846dbaaad67e2d8d/cachecloud-web/src/main/java/com/sohu/cache/web/controller/AppController.java#L866)方法,接着调用AppDao的[getAllAppDescList](https://github.com/sohutv/cachecloud/blob/2973a55cbd11ca1b7ca36226846dbaaad67e2d8d/cachecloud-web/src/main/java/com/sohu/cache/web/service/impl/AppServiceImpl.java#L138)方法,最后在AppDao的[Mapper](https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/mapper/AppDao.xml#L144)文件中做为字符串拼接SQL查询.不正确使用`$`,导致SQL注入.

payload:
/admin/app/list?appParam={sql_injection}

**Comment by haby0** [comment]
In the doAppList method of the AppController class, the user receives [appParam](https://github.com/sohutv/cachecloud/blob/2973a55cbd11ca1b7ca36226846dbaaad67e2d8d/cachecloud-web/src/main/java/com/sohu/cache/web/controller/AppController.java#L852) variable value is assigned to AppSearch instance object as appName, then [getAppDescList](https://github.com/sohutv/cachecloud/blob/2973a55cbd11ca1b7ca36226846dbaaad67e2d8d/cachecloud-web/src/main/java/com/sohu/cache/web/controller/AppController.java#L866) method, and then call AppDao's [getAllAppDescList](https://github.com/sohutv/cachecloud/blob/2973a55cbd11ca1b7ca36226846dbaaad67e2d8d/cachecloud-web/src/main/java/com/sohu/cache/web/service/impl/AppServiceImpl.java#L138) method, and finally in AppDao's [Mapper](https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/mapper/AppDao.xml#L144) file as a string splicing SQL query. Incorrect use of `$`, resulting in SQL injection.

payload:
/admin/app/list?appParam={sql_injection}

**Comment by githubname1024** [comment]
Have fixed in main branch ([692984d](https://github.com/sohutv/cachecloud/commit/692984dc1b77cdee5b6c176cee718fd199db8d7f))
