### ISSUE TITLE
MachineDao.xml#getMachineInfoByCondition 存在SQL注入

### ISSUE THREAD

**Issue by haby0** [sohutv/cachecloud#262]
在MachineManageController类的doMachineList方法中, 然后调用MachineCenterImpl类的[getMachineStats](https://github.com/sohutv/cachecloud/blob/856d02c2de6053eba31225667bdba102b10c694a/cachecloud-web/src/main/java/com/sohu/cache/web/controller/MachineManageController.java#L114)方法, 同时将用户输入的ipLike变量做为方法参数值传入,然后调用MachineDao类的[getMachineInfoByCondition](https://github.com/sohutv/cachecloud/blob/856d02c2de6053eba31225667bdba102b10c694a/cachecloud-web/src/main/java/com/sohu/cache/machine/impl/MachineCenterImpl.java#L493)方法.在MachineDao的[Mapper](https://github.com/sohutv/cachecloud/blob/856d02c2de6053eba31225667bdba102b10c694a/cachecloud-web/src/main/resources/mapper/MachineDao.xml#L53)文件中做为字符串拼接SQL语句, 不正确使用$, 导致SQL注入.

payload:
/manage/machine/list?ipLike={sql_injection}

**Comment by haby0** [comment]
In the doMachineList method of the MachineManageController class, then call the [getMachineStats](https://github.com/sohutv/cachecloud/blob/856d02c2de6053eba31225667bdba102b10c694a/cachecloud-web/src/main/java/com/sohu/cache/web/controller/MachineManageController.java#L114) method, and at the same time pass in the ipLike variable entered by the user as the method parameter value, and then call the [getMachineInfoByCondition](https://github.com/sohutv/cachecloud/blob/856d02c2de6053eba31225667bdba102b10c694a/cachecloud-web/src/main/java/com/sohu/cache/machine/impl/MachineCenterImpl.java#L493) method. In MachineDao's [Mapper](https://github.com/sohutv/cachecloud/blob/856d02c2de6053eba31225667bdba102b10c694a/cachecloud-web/src/main/resources/mapper/MachineDao.xml#L53) in the file as a string splicing SQL statement, incorrect use of $, resulting in SQL injection.


payload:
/manage/machine/list?ipLike={sql_injection}

**Comment by githubname1024** [comment]
Have fixed in main branch ([692984d](https://github.com/sohutv/cachecloud/commit/692984dc1b77cdee5b6c176cee718fd199db8d7f))
