### ISSUE TITLE
Open Redirect

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [sohutv/cachecloud#264]
https://github.com/sohutv/cachecloud/blob/f9dfc98eadcfd7d56821852ece0c73d14cb171e1/cachecloud-web/src/main/java/com/sohu/cache/web/controller/IndexController.java#L25-L32

Allowing unvalidated input to control the URL used in a redirect can aid phishing attacks.

In line 25, ‘redirectUrl’ is regarded to as tainted data,it will be affect line 32.

**Comment by githubname1024** [comment]
There is login and auth check interceptor in project, so ignore this.
