### ISSUE TITLE
安装部署

### ISSUE THREAD

**Issue by Myshiner** [sohutv/cachecloud#267]
您好，我已经安装完成，可以正常登录web后台界面
1. 我现在要导入已存在的redis节点，首先我要在”系统配置管理中添加ssh用户名等相关信息，**在这里”公钥地址“是填写cachecloud服务器上存放cachecloud用户密码的绝对路径吗？**
2. 然后再添加服务器，将redis节点的ip信息加入
3. 导入应用，即填写已有的reids信息
是这样的步骤吗？

**Comment by githubname1024** [comment]
看您的意思是需要将外部的redis服务直接导入到cachecloud进行托管。由于配置文件、数据文件路径与cachecloud部署的redis节点规则可能不一致，所以不支持。
如果需要的话，可根据cachecloud的目录和配置规则，修改已有的redis服务，并且对应给相关目录进行授权。操作较麻烦，但如果存在大量redis实例，可酌情考虑。
建议可考虑在cachecloud中新建集群，然后进行数据同步。实现应用导入。
