### ISSUE TITLE
web界面执行命令后没有结果返回

### ISSUE THREAD

**Issue by Myshiner** [sohutv/cachecloud#268]
您好，我在实例的”执行命令“中执行了info memory等redis命令，但是没有结果返回，是啥原因呢
![J21_N`W7N9L NVUIOJECV4M](https://user-images.githubusercontent.com/48242833/129688633-10350a23-e884-48fe-8eb4-b2d776bb16ff.png)

**Comment by macaty** [comment]
请教

**Comment by 631086083** [comment]
下面有一行红字，非测试应用只能执行已读命令，具体可以看这个文件src/main/java/com/sohu/cache/redis/enums/RedisReadOnlyCommandEnum.java
仅支持以下命令：
    debug,
    exists,
    object,
    ttl,
    type,
    scan,
    get,
    getbit,
    getrange,
    mget,
    setrange,
    strlen,
    hexists,
    hget,
    hgetall,
    hkeys,
    hlen,
    hmget,
    hvals,
    hscan,
    lindex,
    llen,
    lrange,
    scard,
    sismember,
    sscan,
    srandmember,
    zcard,
    zcount,
    zrange,
    zrangebyscore,
    zrank,
    zrevrange,
    zscore,
    zscan,
    dbsize,
    info,
    time,
    lastsave;

**Comment by 631086083** [comment]
是否是连接的proxy，导致命令执行不通过，可以f12看下后台
