### ISSUE TITLE
在机器管理中点击对应的IP后报错

### ISSUE THREAD

**Issue by Myshiner** [sohutv/cachecloud#269]
点击”机器管理“中的IP，有的直接报错
![image](https://user-images.githubusercontent.com/48242833/129689017-07ab4231-9e20-436f-a268-9639e7e3b9b4.png)
报错如下
![image](https://user-images.githubusercontent.com/48242833/129689113-2d2776fa-eff9-42f2-b1af-aa1fe9463ef5.png)

**Comment by githubname1024** [comment]
未提供系统允许日志，无法准确判断。
