### ISSUE TITLE
导入redis集群无数据

### ISSUE THREAD

**Issue by yangmingbai** [sohutv/cachecloud#270]
redis集群版本6.0.9
cachecloud部署版本：2.0版本通过docker部署
现象：集群导入后拉取不到redis集群的数据
<img width="627" alt="1630573952(1)" src="https://user-images.githubusercontent.com/51049448/131817186-a42a73a0-0010-47d9-95de-6dae24f43ae2.png">
<img width="636" alt="1630573908(1)" src="https://user-images.githubusercontent.com/51049448/131817217-bcd542ef-ba41-445e-8bfd-8c63b646adfb.png">
请问是版本不支持吗还是我导入方式错误？我其他的redis集群3.2.4版本的数据就能正常拉取

**Comment by xishian** [comment]
建议贴下cachecloud的日志，方便排查问题
