### ISSUE TITLE
cachecloud-init下载地址打不开

### ISSUE THREAD

**Issue by letianchang** [sohutv/cachecloud#272]
请问cachecloud-init 下载地址是变了吗，为什么打不开呀？

**Comment by macaty** [comment]
自己克隆一个代码库
[root@38d20 cachecloud-2.1]# ls redis-ecs/script/
cachecloud-init.sh  redis-install.sh  redisShake-install.sh  ssh-keygen.sh

**Comment by chenshi6379** [comment]
资源下载地址发生变更,已修复,具体查看 [接入文档](https://github.com/sohutv/cachecloud/blob/main/cachecloud-web/src/main/resources/static/wiki/quickstart/index.md)
