### ISSUE TITLE
升级到cachecloud 2.1版本后，短信和邮件报警接口失效

### ISSUE THREAD

**Issue by beebol** [sohutv/cachecloud#276]
升级到cachecloud 2.1后，后台配置的短信和邮件报警接口无法收到报警。
![image](https://user-images.githubusercontent.com/4249023/144454195-a07a25ec-67b5-4dcf-80a3-c431aa27d7dc.png)
之前的版本是可以正常使用的。

**Comment by wisemeng** [comment]
> 升级到cachecloud 2.1后，后台配置的短信和邮件报警接口无法收到报警。 ![图像](https://user-images.githubusercontent.com/4249023/144454195-a07a25ec-67b5-4dcf-80a3-c431aa27d7dc.png) 之前的版本是可以正常使用的。

**Comment by wisemeng** [comment]
@beebol 你好 请问下报警接口是怎么实现的 有具体的吗

**Comment by githubname1024** [comment]
@beebol 您好。如果是从1.x升级到2.1版本，由于项目模块变更，发送邮件改成更灵活的方式，需要自己实现。可参照1.X版本中cachecloud-open-common模块中的EmailComponentImpl和MobileAlertComponentImpl中的实现，重写2.1版本中的cachecloud-custom模块下的DefaultWeChatComponent和DefaultEmailComponent中对应的方法。
注：手机或邮件告警相关配置常量从ConstUtils转移到AlertUtils类。在拷贝上述实现时，请注意。
