### ISSUE TITLE
管理机器页面无法正常显示

### ISSUE THREAD

**Issue by 364427800** [sohutv/cachecloud#28]
我在自己的eclipse上部署完成顺利启动，成功登陆后，从admin进入管理后台，其他页面都正常显示，但是“管理机器”页面无法正常显示，一片空白,后台也没有ERROR

**Comment by 364427800** [comment]
找到原因了：我的MYSQL版本是5.7.9,  自5.7.6之后加入了关键字：virtual    ， 该项目的创建表的时候，其中一张表：machine_info  中引用到了该字段 virtual  ，导致代码执行报错，页面无法显示。
强烈建议作业修改代码中 virtual字段，防止与数据库保留字段冲突。

**Comment by carlosfu** [comment]
> 找到原因了：我的MYSQL版本是5.7.9, 自5.7.6之后加入了关键字：virtual ， 该项目的创建表的时候，其中一张表：machine_info 中引用到了该字段 virtual ，导致代码执行报错，页面无法显示。
> 强烈建议作业修改代码中 virtual字段，防止与数据库保留字段冲突。

这个问题之前已经修复，更新下代码
