### ISSUE TITLE
cachecloud2.1版本修改redis6.0密码为空不成功

### ISSUE THREAD

**Issue by mali0512** [sohutv/cachecloud#283]
cachecloud平台修改redis6.0的版本的密码，设置密码为空，日志报成功了，但是实际没有成功。修改为非空，能正常修改成功。

**Comment by githubname1024** [comment]
由于redis6.0.0-6.0.8 源码存在bug , 如果设置密码为空 会导致设置为空字符串，已在6.0.9 修复该问题。

参考redis6.0.x changelog : https://raw.githubusercontent.com/redis/redis/6.0/00-RELEASENOTES
================================================================================
Redis 6.0.9     Released Mon Oct 26 10:37:47 IST 2020
================================================================================
Bug fixes:
* INFO report real peak memory (before eviction) (#7894)
***.  Allow requirepass config to clear the password (#7899). *** 
* Fix config rewrite file handling to make it really atomic (#7824)
* Fix excessive categories being displayed from ACLs (#7889)
* Add fsync in replica when full RDB payload was received (#7839)
* Don't write replies to socket when output buffer limit reached (#7202)
* Fix redis-check-rdb support for modules aux data (#7826)
* Other smaller bug fixes
建议：

使用redis 6.0.9 以后版本
升级cachecloud源码 ceb62df
