### ISSUE TITLE
二开疑问;

### ISSUE THREAD

**Issue by sxy19930616** [sohutv/cachecloud#287]
1:我们想基于cachecloud目前开源项目代码二次开发下,后续开发好后,能不能部署在k8s容器中,我看目前没有明确的资料可以参考.如果不能 是基于哪个方面的考虑?
2:如果我们只有6个机器 能不能同时支持单机,哨兵,集群三个模式,他们是根据什么进行环境隔离的,是拷贝多个conf文件做配置然后启动多个实例么?

**Comment by githubname1024** [comment]
1. cachecloud 可以部署在k8s容器中，确保与部署redis的机器网络通讯正常即可。
2. 部署redis的机器可以支持多个redis实例部署的，且实例可在不同的模式（单机、哨兵、集群）下。同一台机器中的redis实例，是通过带有端口号的相关文件（配置文件、aof文件、日志文件等）区分。

**Comment by githubname1024** [comment]
目前没有，如果需要的话，可以自己开发实现。后期如果使用场景较多，可以考虑纳入计划。
