### ISSUE TITLE
应用导入或者应用申请选择哨兵时候 无法混合选择

### ISSUE THREAD

**Issue by lunsse** [sohutv/cachecloud#288]
![image](https://user-images.githubusercontent.com/89910266/179161543-38d26172-a3ec-4450-9dda-12f246f3a8f0.png)
三台机器做 三个redis + sentinel 模式 无法选择 sentinel
![image](https://user-images.githubusercontent.com/89910266/179161769-da7b3875-a071-4931-9d6c-4c751420ba77.png)
![image](https://user-images.githubusercontent.com/89910266/179161837-df77ea00-9b2f-4fc0-a011-be6e42d27124.png)
sentinel机器选择是空

版本（2.2 2.1 分支 master main 都有这样的情况）

**Comment by githubname1024** [comment]
目前cachecloud，默认redis部署机器和sentinel机器隔离。
如需单台机器支持混合部署，即支持部署sentinel节点和redis节点，可自行修改项目的前端页面中的逻辑控制，见/webapp/WEB-INF/manage/appAudit/deploy/appDeployDetail.jsp，在选择sentinel机器部分去掉machine.info.type筛选限制。 然后再进行部署测试即可。

**Comment by githubname1024** [comment]
目前cachecloud，默认redis部署机器和sentinel机器隔离。
如需单台机器支持混合部署，即支持部署sentinel节点和redis节点，可自行修改项目的前端页面中的逻辑控制，见/webapp/WEB-INF/manage/appAudit/deploy/appDeployDetail.jsp，在选择sentinel机器部分去掉machine.info.type筛选限制。 然后再进行部署测试即可。

**Comment by githubname1024** [comment]
cachecloud由于考虑redis服务高可用，默认redis部署机器与sentinel机器隔离。此业务场景属于特例，暂不合并到开源代码中。如有相关问题，可参考上一comment自行修改。
