### ISSUE TITLE
定时任务表名在程序里是大写，导致启动程序报错找不到对应的表

### ISSUE THREAD

**Issue by wangshuai1810** [sohutv/cachecloud#292]
定时任务的表名在程序里统一写成小写是不是更符合规范啊

**Comment by githubname1024** [comment]
烦请告知一下，数据库的版本，和当前的报错信息。我们这边check一下

**Comment by githubname1024** [comment]
Thank you for pointing out this bug. We have fixed it in main branch.[05703bf](https://github.com/sohutv/cachecloud/commit/05703bfd2d7494556b6e1c345e5d527def021598)
