### ISSUE TITLE
mvn编译cachecloud2.1和2.2版本均报错

### ISSUE THREAD

**Issue by wwloo2018** [sohutv/cachecloud#294]
下载cachecloud2.2和2.1的release版本，使用mvn报错均出现如下报错：是什么原因呢？ 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project cachecloud-web: Compilation failure: Compilation failure:
[ERROR] /database/cachecloud-2.2/cachecloud-web/src/main/java/com/sohu/cache/util/Pair.java:[28,20] 程序包javafx.beans不存在
[ERROR] /database/cachecloud-2.2/cachecloud-web/src/main/java/com/sohu/cache/util/Pair.java:[65,17] 找不到符号
[ERROR] 符号:   类 NamedArg
[ERROR] 位置: 类 com.sohu.cache.util.Pair<K,V>
[ERROR] /database/cachecloud-2.2/cachecloud-web/src/main/java/com/sohu/cache/util/Pair.java:[65,41] 找不到符号
[ERROR] 符号:   类 NamedArg
[ERROR] 位置: 类 com.sohu.cache.util.Pair<K,V>
[ERROR] -> [Help 1]

**Comment by githubname1024** [comment]
@wwloo2018 请提供一下jdk详细版本
