### ISSUE TITLE
怎么把cachecloud迁移到新的机器上

### ISSUE THREAD

**Issue by czxin788** [sohutv/cachecloud#295]
我们现在用cachecloud管理了几套redis cluster。
cachecloud是单独部署在一个ECS机器上的，但是这个机器要到期了，我们想把cachecloud迁移到其他机器上，请问怎么操作

**Comment by githubname1024** [comment]
@czxin788 是仅迁移cachecloud，由cachecloud管理的redis cluster不动吗？
如果是的，首先将cachecloud依赖的数据库（mysql、和redis(有些cachecloud版本不依赖，如有，具体可看配置文件中是否有配置)）进行备份并部署到新机器。
确保新的部署cachecloud的机器上，存放有对应目录的文件，如配置有ssh密钥，则需进行确认。
拷贝cachecloud 程序包到新机器，然后进行启动。

如操作过程中有问题，可以在追加。

**Comment by czxin788** [comment]
非常感谢。
是的，仅迁移cachecloud，cachecloud管理的redis cluster不动。

还有个问题想咨询一下，就是关闭cachecloud，对被管理的redis cluster没影响对吧

**Comment by githubname1024** [comment]
关闭cachecloud，对被管理的redis 服务本身是没有影响的。

**Comment by czxin788** [comment]
谢谢
