### ISSUE TITLE
运行脚本 执行失败，

### ISSUE THREAD

**Issue by gzp1234** [sohutv/cachecloud#298]
运行脚本 执行失败，手动安装redis ，创建用户，后台也建立不了redis

**Comment by githubname1024** [comment]
已修复init脚本bug。从提供的日志中，发现连接部署机器ip:port出现失败，请确认服务器是否有端口访问限制。
![图片](https://user-images.githubusercontent.com/100768089/210693506-a0579ee8-c537-4e53-b44a-079dc8a17112.png)
