### ISSUE TITLE
chown -R $1 /var/run出错

### ISSUE THREAD

**Issue by NightAlexLy** [sohutv/cachecloud#3]
chown: changing ownership of `/var/run/vmblock-fuse/dev': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/d4753559': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/7b1fd18b': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/35754c3f': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/246b73b1': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/b5e3c9ca': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/ea1762f1': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/799fd622': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/d67433d2': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/7883d1eb': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir/b568c856': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse/blockdir': Function not implemented
chown: changing ownership of `/var/run/vmblock-fuse': Function not implemented

**Comment by carlosfu** [comment]
> chown: changing ownership of /v

请问是在root账户下执行的吗？
