### ISSUE TITLE
代码中的疑问

### ISSUE THREAD

**Issue by ruixiu** [sohutv/cachecloud#30]
com.sohu.cache.async.AsyncServiceImpl.java第80行和第81行完全相同，确定需要两次吗？

**Comment by carlosfu** [comment]
> com.sohu.cache.async.AsyncServiceImpl.java第80行和第81行完全相同，确定需要两次吗？

确定，理论上执行三次也可以，当然这种写法容易产生歧义。

cachecloud很多任务：比如收集Redis实例信息等等都是通过异步线程池完成的，并把future放入到队列中，执行两次是为了加速队列的消费速度。
