### ISSUE TITLE
关于 Pika 支持的疑问

### ISSUE THREAD

**Issue by klboke** [sohutv/cachecloud#304]
### 环境信息
- cachecloud.version: 3.2

你好，我看到应用部署时支持 Pika 的应用类型，如下截图
<img width="389" alt="image" src="https://user-images.githubusercontent.com/18591662/230528560-2ad25a50-490b-43ab-87f2-5a715dc0a927.png">
但是在应用申请提交的时候并没有，所以请问下这里列出来的几种模式都是完整支持的么

**Comment by githubname1024** [comment]
目前cachecloud拥有完整申请-部署链路的，仅有ReidsCluster、Sentinel+Redis、Redis-Standalone. 
Pika的方式不再支持。

**Comment by klboke** [comment]
好的，感谢回复
