### ISSUE TITLE
3.2无法正常编译

### ISSUE THREAD

**Issue by beebol** [sohutv/cachecloud#306]
mvn clean compile install -Ponline
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.9.RELEASE/spring-boot-dependencies-2.2.9.RELEASE.pom: unexpected markup <!d (position: START_DOCUMENT seen ...governing permissions and\n limitations under the License.\n\n-->\n<!d... @18:4)  @ /root/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.9.RELEASE/spring-boot-dependencies-2.2.9.RELEASE.pom, line 18, column 4
[FATAL] Non-parseable POM /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Hoxton.SR4/spring-cloud-dependencies-Hoxton.SR4.pom: unexpected markup <!d (position: START_DOCUMENT seen ...governing permissions and\n limitations under the License.\n\n-->\n<!d... @18:4)  @ /root/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Hoxton.SR4/spring-cloud-dependencies-Hoxton.SR4.pom, line 18, column 4
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:sp

**Comment by githubname1024** [comment]
@beebol 
此异常非cachecloud项目本身的异常。
请确认maven配置，或仓库中依赖项是否下载成功。如上述两个均无问题，可根据异常提示修复mvn打包问题。

**Comment by KeithTt** [comment]
我用这条指令也编译不了 然后直接用 `mvn clean package` 编译的
