### ISSUE TITLE
在启动进程的时候显示表不存在，表名大写

### ISSUE THREAD

**Issue by 2018jm** [sohutv/cachecloud#310]
![image](https://github.com/sohutv/cachecloud/assets/123924368/4775c257-b7b4-492c-9d41-12ec522f7163)
为什么这个表名是大写，使用sql添加出来数据库是小写的
![image](https://github.com/sohutv/cachecloud/assets/123924368/3c137670-45a2-48f4-ae7c-203f7e69860b)
![image](https://github.com/sohutv/cachecloud/assets/123924368/58e62e11-ce5c-442e-8253-b14f2fcb468c)

**Comment by githubname1024** [comment]
@2018jm 请确认部署的是哪个版本的，3.2版本sql 是大写的。
