### ISSUE TITLE
为什么会在下载redis安装包名字上加个-make

### ISSUE THREAD

**Issue by hymvp** [sohutv/cachecloud#314]
在主机的安装日志install.log中发现报错:
--2023-08-17 23:41:10--  https://download.redis.io/releases//redis/redis-5.0.8-make.tar.gz
Resolving download.redis.io (download.redis.io)... 45.60.125.1
Connecting to download.redis.io (download.redis.io)|45.60.125.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-08-17 23:41:12 ERROR 404: Not Found.

下载的地址：https://download.redis.io/releases//redis/redis-5.0.8-make.tar.gz，包的名字里会多个-make。
在后台的配置中没有发现包的名字带“-make”
![image](https://github.com/sohutv/cachecloud/assets/10459396/8b65029b-b899-471f-85ca-e4fc16189034)

**Comment by githubname1024** [comment]
不带make的为redis源码，需要经过编译后，才能部署安装。故分为源码地址（redis官方地址），和编译后地址。
在资源管理——Redis资源管理中，配置有源地址，配置完之后，需要编译并推送到仓库地址（资源管理——仓库配置）后，方可使用。
