### ISSUE TITLE
ssh 增加证书认证功能

### ISSUE THREAD

**Issue by laochen** [sohutv/cachecloud#32]
我在ssh用户名、密码模式上新增了ssh证书认证，希望能合并进来, https://github.com/laochen/cachecloud

**Comment by carlosfu** [comment]
谢谢，可以发一个pull requests到dev分支，我们review一下。

**Comment by sohutv** [comment]
> 我在ssh用户名、密码模式上新增了ssh证书认证，希望能合并进来, https://github.com/laochen/cachecloud

我看了一下合并的代码，合并后配置变多了，会让别人不太适应，而且没有普适性。
所以最终没有合并到master，如果有需要您自己做定制化就可以了，感谢提交

**Comment by zhuxianjun1983** [comment]
由于公司服务器禁用SSH用户密码登录，希望能增加SSH KEY登录方式。
