### ISSUE TITLE
部署 cluster 时，是否可以指定 dir 目录，新增配置好像渲染不出来

### ISSUE THREAD

**Issue by yuniverser** [sohutv/cachecloud#325]
复制之前 cluster 里面已有的能渲染处理啊
<img width="1555" alt="redis1" src="https://github.com/sohutv/cachecloud/assets/151110090/c50971d4-a547-40dc-8ab9-797819299ffc">
自己新增的不能渲染
<img width="345" alt="redis2" src="https://github.com/sohutv/cachecloud/assets/151110090/7d18cf3a-5e76-406a-bbdf-f5fb18bb0404">

另外还有一个问题，6.0 版本中，是否支持使用 acl 文件控制 user 权限

**Comment by githubname1024** [comment]
1. 关于dir配置，如需修改，建议自己修改源码，变量目前不识别。可以参考代码中，截图中的cluster-config-file的值替换逻辑。
2. acl 文件，也可自己定制开发，目前暂未支持。

**Comment by yuniverser** [comment]
好的，感谢回复
