### ISSUE TITLE
这个又是啥问题，我的机器内存三台是251G。

### ISSUE THREAD

**Issue by LonelyBean** [sohutv/cachecloud#332]
![1718189024644](https://github.com/sohutv/cachecloud/assets/105805576/cf3aa59e-e03f-4f0d-862a-86d4b17a81db)

**Comment by githubname1024** [comment]
从运维角度，1个redis节点内存不超过10G较好，所以单个节点有最大内存限制。
你设置的单个节点80G，远超过10G了。
如确有需要，可自行修改代码调整，见com.sohu.cache.task.constant.TaskConstants的参数MAX_MEMORY_LIMIT大小。
