### ISSUE TITLE
安装希望提供侵入性小的方式

### ISSUE THREAD

**Issue by gumutianqi** [sohutv/cachecloud#36]
脚本包含了很多东西，一半需要监控管理，服务器上环境已经有了，类似jdk，redis，nginx，mysql，mongodb应该是都有的，所以能否提供一个标明依赖那些第三方库或者包的安装方式，说明在哪儿调整配置文件就好了

**Comment by carlosfu** [comment]
> 脚本包含了很多东西，一半需要监控管理，服务器上环境已经有了，类似jdk，redis，nginx，mysql，mongodb应该是都有的，所以能否提供一个标明依赖那些第三方库或者包的安装方式，说明在哪儿调整配置文件就好了

jdk、mysql、nginx、maven安装说明？？

**Comment by gumutianqi** [comment]
@carlosfu 在服务器上jdk、mysql、redis、nginx、maven环境都有已经存在了，那么在这些环境都有的情况下如何最小侵入性安装cachecloud呢，而不是执行install.sh全新安装

**Comment by geekyijun** [comment]
cachecloud-init.sh脚本初始化工作主要：
1. 加入cachecloud账户，
2. 建立统一的目录结构
3.安装redis
前两部不存在引入性，都是cachecloud自身的初始化。
最后一步安装redis 即使服务器上已存在redis服务也不会有影响。
