### ISSUE TITLE
集群模式无法显示已启动的实例

### ISSUE THREAD

**Issue by sharego** [sohutv/cachecloud#37]
# 环境
- redhat 7.2  x64
- redis-3.0.7
- cachecloud  03431d7210079a276738f25be63a423efc7ed17b (Apr 21)
# 步骤
- 提交应用申请: 160G, Redis-Cluster
- 审批应用申请:  26台机器，每台4主实例/8主实例, 下一台节点启动从实例(也就是一台共启动8/16实例), 实例内存大小1024/10240/20480
# 现象
- 由于实例过多, 审批处理页面会长时间等待
- 审批处理会正常结束，并返回到审批列表界面
- 应用详情拓扑结构中实例为空，但**对应主机上的实例已经启动**
- 数据库里：app_desc表应用状态变为 1 （已申请未审批）（界面显示申请中），instance_info表查询实例为空
- 日志 (仅截取了部分)

```
2016-04-22 16:51:36.605 {http-nio-8086-exec-10} INFO  com.sohu.cache.redis.impl.RedisDeployCenterImpl - masterShell:host=10.161.12.28
;shell=redis-server /opt/cachecloud/conf/redis-cluster-6434.conf > /opt/cachecloud/logs/redis-6434-201604221651.log 2>&1 &
2016-04-22 16:51:36.917 {http-nio-8086-exec-10} WARN  com.sohu.cache.redis.impl.RedisDeployCenterImpl - runInstance-fallback : redis-cli -h 10.161.12.28 -p 6434 shutdown
......
{http-nio-8086-exec-10} ERROR com.sohu.cache.redis.impl.RedisDeployCenterImpl$6 - java.net.ConnectException: 
Connection refused

......
{http-nio-8086-exec-10} ERROR com.sohu.cache.redis.impl.RedisDeployCenterImpl - host:10.161.12.29;port:6433 n
ot run

......
10.161.12.49:1024:10.161.12.24,appAuditId:12, result is true
```
# 排除
- 防火墙等网络不通
# 疑问
- 不明白Deploy之后执行 redis-cli shutdown

**Comment by carlosfu** [comment]
@sharego 

不明白Deploy之后执行 redis-cli shutdown ?

其实并没有shutdown，而是打印了一行日志，因为开启一个应用有时候会出现问题，但是这个做成事务是很难的，所以做了一个简单的redis-cli shutdown

详细原因，欢迎加群qq：534429768进行交流
