### ISSUE TITLE
部署端口可配置？

### ISSUE THREAD

**Issue by TrumanDu** [sohutv/cachecloud#41]
@carlosfu 
hi,是否支持端口自定义？
**建议特性**
- 部署redis安装包上传
- 生成实例端口信息位置太偏僻。
- ssh账户通过上层应用添加管理是否更好？

期待回复。。。

**Comment by carlosfu** [comment]
> hi,是否支持端口自定义？
> 建议特性
> 
> 部署redis安装包上传
> 生成实例端口信息位置太偏僻。
> ssh账户通过上层应用添加管理是否更好？
> 期待回复。。。

@TrumanDu 
你好，你的描述不是很清楚，或者我不太能理解你要表达什么？
可以加qq群：534429768联系我。
