### ISSUE TITLE
是否支持机器的ssh账号密码独立配置

### ISSUE THREAD

**Issue by yudongdai** [sohutv/cachecloud#43]
1.目前的ssh账号密码应该是统一配置的
2.实际线上环境中，每台机器的ssh的账号密码都不一样

能否支持新增机器时配置ssh的账号密码

**Comment by carlosfu** [comment]
> 1.目前的ssh账号密码应该是统一配置的
> 2.实际线上环境中，每台机器的ssh的账号密码都不一样
> 
> 能否支持新增机器时配置ssh的账号密码

暂时不支持，不过这个开发起来不太难，如果需求大的话，我们可以兼容一下，但是我们觉得在内网用统一的密码不是很大的问题，也便于管理。

**Comment by hawk2036** [comment]
这个问题也困扰着我们，后来发现确实是不一致的密码导致的，目前也只能变通统一的密码
