### ISSUE TITLE
是否支持redis实例的配置在页面展示

### ISSUE THREAD

**Issue by yudongdai** [sohutv/cachecloud#44]
最新的版本，没看到redis的配置界面化展示按钮，此功能是否已经被移除。

**Comment by carlosfu** [comment]
> 最新的版本，没看到redis的配置界面化展示按钮，此功能是否已经被移除。

没有移除，已经添加到应用统计界面，注意这个配置修改会修改应用下所有的配置。

后期我们会开发只针对节点配置进行修改的界面，这个比较容易做。
http://cachecloud.github.io/2016/04/17/v2%E8%AE%A1%E5%88%92/

**Comment by yudongdai** [comment]
已经找到了，点击拓扑结构->ID，进去就看到了，
