### ISSUE TITLE
在监控页面添加一个功能

### ISSUE THREAD

**Issue by xxlaila** [sohutv/cachecloud#47]
能不能在监控页面  加上一个keys 排名最大的 前10个 或者加一个这种自己查询的条件，  我就经常遇到开发的来说 能不能查询那个keys最大那个keys占用空间最小，添加一个可以看到最大的可以查看最小的排名。作为使用者，在这里谢谢开发者

**Comment by carlosfu** [comment]
> 能不能在监控页面 加上一个keys 排名最大的 前10个 或者加一个这种自己查询的条件， 我就经常遇到开发的来说 能不能查询那个keys最大那个keys占用空间最小，添加一个可以看到最大的可以查看最小的排名。作为使用者，在这里谢谢开发者

后期版本中会加入这个功能，但是对于开发者来说，big key很重要，但是使用big key的频率更为重要。

**Comment by xxlaila** [comment]
在客户端在添加一查询keys 大小的功能。通过web页面进行操作、展示。例如：在web界面有一个查询当前keys大小（可以根据顺序进行排列）。也web页面点击，然后发送到客户端在客户端执行之后结果在展示在web界面
