### ISSUE TITLE
扩容申请被驳回后，管理员操作按钮消失

### ISSUE THREAD

**Issue by yudongdai** [sohutv/cachecloud#49]
登陆管理员
点击：管理后台->全局统计

故障：应用下线和应用运维按钮消失了

**Comment by carlosfu** [comment]
> 登陆管理员
> 点击：管理后台->全局统计
> 
> 故障：应用下线和应用运维按钮消失了

是不是应用已经下线了？

**Comment by yudongdai** [comment]
应用没有下线，你模拟一次就知道了。

再次申请扩容，管理员通过后，按钮又出现了。
