### ISSUE TITLE
主机账户管理

### ISSUE THREAD

**Issue by dengw** [sohutv/cachecloud#5]
cachecloud目前对新添加进去的主机，默认账户密码都是local.properties和online.properties配置里面的cachecloud.machine.username、cachecloud.machine.password字段，并且都是以明文的方式存在，建议版主加个host之类的表，专门用来管理各个主机（包括用户密码，毕竟明文显示是很不安全的）。

**Comment by carlosfu** [comment]
> cachecloud目前对新添加进去的主机，默认账户密码都是local.properties和online.properties配置里面的cachecloud.machine.username、cachecloud.machine.password字段，并且都是以明文的方式存在，建议版主加个host之类的表，专门用来管理各个主机（包括用户密码，毕竟明文显示是很不安全的）。

你说的很有道理，我们当时考虑易用性，对于内网环境还是相对信任的态度，这个后期可以考虑修改一下。
