### ISSUE TITLE
日志文件被删除的风险

### ISSUE THREAD

**Issue by yudongdai** [sohutv/cachecloud#50]
1.目前日志的记录方式是通过启动时重定向输出实现的
2.一旦日志文件被删除了，那么以后的日志就没办法写入
3.文件会显示deleted状态

redis源生的做法会重新open日志文件

**Comment by carlosfu** [comment]
现在使用的是 redis-server xx.conf > xx.$timestamp}.log的方式来启动Redis，如果日志被删除确实存在你说的的问题，但是有两点：
1. 一般日志不会删除。
2. 采用了${timestamp}作为日志的文件名，是为了记录每次启动redis时候把日志文件分割开，便于查询。

如果你想使用logfile的方式进行配置，可以修改cachecloud源码中的RedisConfigEnum和RedisProtocol类。
