### ISSUE TITLE
cluster password

### ISSUE THREAD

**Issue by jsonzhong** [sohutv/cachecloud#59]
我现在用的是3.2.3，然后想使用集群密码，但是配置文件加上密码后，使用cachecloud启动说“开启失败 msg:undefined”，但是通过机器查询是启动成功的，而且集群也是能使用的，但是cachecloud应用列表里面都是没有开启的。请问你们有计划将这个进行完善吗？

**Comment by geekyijun** [comment]
下一个版本加入密码功能，感谢关注。
