### ISSUE TITLE
cachecloud客户端接入除了jedis是否支持其它客户端

### ISSUE THREAD

**Issue by AirJay** [sohutv/cachecloud#7]
我们环境中有c，php，go之类的应用，是否能支持除java外的客户端接入？

谢谢

**Comment by sohutv** [comment]
> 我们环境中有c，php，go之类的应用，是否能支持除java外的客户端接入？

可以的，cachecloud有restapi，能够返回redis sentinel、redis-cluster的分片信息，然后你在用你的客户端进行初始化。
可以参考一下 http://redis.io/clients其中带星号和笑脸的客户端(但是客户端要支持setinel和cluster模式)

**Comment by cycorey** [comment]
请问支持不支持java的 redisson库？

**Comment by geekyijun** [comment]
默认支持Jedis，其他api访问通过restAPI获取redis节点信息初始化，见wiki:https://github.com/sohutv/cachecloud/wiki/4.%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3#cc2-1
