### ISSUE TITLE
服务器监控没有数据

### ISSUE THREAD

**Issue by ztajy** [sohutv/cachecloud#70]
您好，我是通过应用导入功能将现有redis cluster导入进cachecloud的，在后台管理的机器管理中添加了新机器，但点击机器列表中的监控按钮，展示的机器监控页面一直没有数据，看了下代码，是查询的server和server_stat表，为啥这两个表一直都没数据呢？这两个表和machine_info、machine_statistics在用途上有什么区别，还请不吝赐教，谢谢。

**Comment by carlosfu** [comment]
@ztajy 这个功能将在下一个版本开放，目前master分支为了合并公司内代码所以添加了这个【监控】选项，如果有需要可以进qq群：534429768讨论。

**Comment by ztajy** [comment]
谢谢，了解了。

**Comment by carlosfu** [comment]
@ztajy 看下这个文档 https://cachecloud.github.io/2017/02/06/1.3.%E6%9C%BA%E5%99%A8%E7%9B%91%E6%8E%A7%E5%8A%9F%E8%83%BD/
