### ISSUE TITLE
local的war包没有问题，但是online的war包起动不了

### ISSUE THREAD

**Issue by wk1281472252** [sohutv/cachecloud#71]
![image](https://cloud.githubusercontent.com/assets/20434131/22731906/4bd7322a-ee27-11e6-8037-ee00f6bb7328.png)
![image](https://cloud.githubusercontent.com/assets/20434131/22731920/59a8f8de-ee27-11e6-8ae2-d1b2c10fd635.png)
local.properties和online.properties中关于mysql的配置一致，为什么local生成的war包可以跑，online的报错，谢谢 0.0

**Comment by carlosfu** [comment]
@wk1281472252 这个应该是数据库权限的问题

**Comment by wk1281472252** [comment]
@carlosfu  
![image](https://cloud.githubusercontent.com/assets/20434131/22810448/cc7b9950-ef73-11e6-8bf1-3bcde705975d.png)
给了最大的权限啊 0.0

**Comment by rookie07** [comment]
你好，请问你的这个问题解决了吗？我也报相同的错误，但是数据库也是给了最大的权限。
