### ISSUE TITLE
导入SQL有问题

### ISSUE THREAD

**Issue by zrx879582094** [sohutv/cachecloud#73]
代码中的脚本需要指定数据库名,并且在linux下'-'是被禁止用于名称的,建议第一行添加
create database cache_cloud;
USE cache_cloud;
并且修改或添加my.cnf的配置
[mysqld] 
character_set_server=utf8
collation-server=utf8_general_ci
[client] 
default-character-set=utf8

第二个问题,修改表结构的问题
在MySQL 5.7 CentOS7.3 环境下
SQL的第1013行有问题.报错
ERROR 1067 (42000) at line 1015: Invalid default value for 'service_time'
修改my.cnf,
[mysqld] 下面添加
sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
explicit_defaults_for_timestamp=1
###end
原文连接http://www.cnblogs.com/findgor/p/5493254.html

**Comment by zrx879582094** [comment]
5.7添加用户问题
报错 ERROR 1054 (42S22): Unknown column 'password_last_changed' in 'mysql.user'
use mysql;
ALTER TABLE user ADD Create_tablespace_priv ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER Trigger_priv; 
ALTER TABLE user ADD plugin CHAR(64) NULL AFTER max_user_connections; 
ALTER TABLE user ADD authentication_string TEXT NULL DEFAULT NULL AFTER plugin; 
ALTER TABLE user ADD password_expired ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER authentication_string;

**Comment by GitHubMota** [comment]
'-'倒是没被禁止用于数据库名称的， 可以使用 create database `cache-cloud`;  ， 不过确实强烈建议名称改成cache_cloud等。

**Comment by huangzhuxing** [comment]
谢谢，解决了我的页面中文乱码问题
