### ISSUE TITLE
cachecloud能直接加入生产的redis集群吗

### ISSUE THREAD

**Issue by bylijinnan** [sohutv/cachecloud#78]
看《redis开发与运维》这本书，说cacheclound是通过info命令来收集信息监控，不会对redis集群性能产生影响。

但还是想确认一下，能否直接应用到生产上。我们生产上已有redis集群，准备加入cacheclound做监控。

**Comment by carlosfu** [comment]
@bylijinnan 可以的。如果还需要了解，可以加QQ群：534429768
