### ISSUE TITLE
机器监控页面net标签在有数据的情况下显示no data

### ISSUE THREAD

**Issue by EriconYu** [sohutv/cachecloud#79]
在机器监控页面中（/server/index.do?ip=x.x.x.x），net显示数据的情况下，仍然会显示no data。

net.jsp文件中有如下代码：

> <c:if test="${empty cpu}">

将其改为：

> <c:if test="${empty net}">

即可解决问题。

**Comment by githubname1024** [comment]
Thanks for your advice. We have fix it.
