### ISSUE TITLE
wiki文档《4.客户端端接入文档》中《3. redis客户端的异常统计》里面的链接无法打开

### ISSUE THREAD

**Issue by EriconYu** [sohutv/cachecloud#81]
链接如下：
http://cachecloud.github.io/2016/05/31/cachecloud%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BB%9F%E8%AE%A1%E4%B8%8A%E6%8A%A5%E5%8A%9F%E8%83%BD/ 
经过测试，以下链接可以打开：
https://cachecloud.github.io/2016/05/31/cachecloud%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%BB%9F%E8%AE%A1%E4%B8%8A%E6%8A%A5%E5%8A%9F%E8%83%BD/

**Comment by carlosfu** [comment]
@EriconYu 应该已经可以。
