### ISSUE TITLE
启动时锁表问题

### ISSUE THREAD

**Issue by bylijinnan** [sohutv/cachecloud#84]
启动不了，启动时报锁表，DBA查看是有多个会话发起了下面这个查询：
select from qrtz_locks where sched_name ='CacheCloudScheduler' and lock_name ='TRIGGER_ACCESS' for update

另外请问这个查询是在哪里发起的？在源码没看到有对这个表的操作

**Comment by carlosfu** [comment]
@bylijinnan 请贴下详细日志。cachecloud使用quartz框架做任务调度，以QRTZ开头的表是quartz使用。所以内部你看不到代码。
