### ISSUE TITLE
导入的应用与申请新建的应用有哪些区别

### ISSUE THREAD

**Issue by sharego** [sohutv/cachecloud#86]
客户端连接，Redis的**监控**与**实例管理**等方面；可否通过导入的方式来进行cachecloud的版本升级(比如从0.X到1.2)

**Comment by carlosfu** [comment]
导入应用：支持基础的监控和报警
申请新建：除了监控和报警，还有全部的运维功能。
具体可以参考：https://cachecloud.github.io/2016/04/17/%E5%B7%B2%E5%AD%98%E5%9C%A8Redis%E6%8E%A5%E5%85%A5CacheCloud/
