### ISSUE TITLE
执行 cachecloud-init.sh时出现问题

### ISSUE THREAD

**Issue by jiangzif** [sohutv/cachecloud#87]
环境是centos6.5
试过命令
 sh cachecloud-init.sh ${XXX}
 sh cachecloud-init.sh XXX
 sh cachecloud-init.sh [XXX]
均提示一下信息：
: command not found line 2: 
: command not found line 11: 
: invalid option nameine 12: set: nounset

**Comment by carlosfu** [comment]
@jiangzif 看下第二个问题 https://cachecloud.github.io/2016/04/12/CacheCloud%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98/

**Comment by jiangzif** [comment]
@carlosfu 你好，看到过解决方案。这个文件并没有进行任何更改。在windows环境上下载，可以通过版本控制查看到没有变更，然后ftp上传至服务器运行就会出现这个错误
