### ISSUE TITLE
mysql5.7 导入sql语句时，timestamp  DEFAULT值报错

### ISSUE THREAD

**Issue by xujingbin** [sohutv/cachecloud#89]
mysql5.7 导入sql语句时报错，timestamp  DEFAULT值报错，删除default值才导入成功， 报错语句： `service_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '上线时间',

**Comment by geekyijun** [comment]
抱歉，没有对mysql 5.7做兼容性测试。

**Comment by BrandynX** [comment]
这是由于MySQL 5.7默认sql_mode配置比较严格，方法有2。
1.my.cnf中配置sql_mode=''
2.show variables like 'sql_mode'，把其中带zero的属性去掉，并在my.cnf中设置。
可以重启或set global设置

**Comment by GitHubMota** [comment]
同碰到这个问题， 也是在mysql 5.7上的， 为什么不把'0000-00-00 00:00:00'改成CURRENT_TIMESTAMP。或者改成最小时间：1970-01-01 08:00:01
