### ISSUE TITLE
机器管理-新添加机器后没有显示在列表

### ISSUE THREAD

**Issue by snake1361222** [sohutv/cachecloud#9]
如题..数据库内有记录

**Comment by carlosfu** [comment]
> 如题..数据库内有记录

因为我们收集机器的信息(几个性能指标)使用的quartz，会延迟一分钟，可以从后台的quartz管理查到具体的时间，不过这个对于应用的开启没有影响。

稍后我会改一下这种不友好的处理方式。

**Comment by carlosfu** [comment]
> 如题..数据库内有记录

已经修复，添加完机器后，立即显示，机器的性能信息一分钟后生效。
