### ISSUE TITLE
部署的时候始终提示“正在部署，请等待..........”

### ISSUE THREAD

**Issue by kilonapeng** [sohutv/cachecloud#95]
我在机器的PC上虚拟了一台redhat7.2，申请了应用后用admin处理，但不管是cluster还是standalone开始部署后始终提示“正在部署，请等待......”，后面的省略号就一直延长，等不到结束。重新打开审批流程后之前的进度都没有了。我看这台虚拟机上已经有了配置文件（不管什么cluster还是standalone都是只有一个配置文件），redis进程也已经起来了。
1、请问这是什么问题？
2、之前部署的应用怎么删除，是把配置文件删除，再从mysql里清理对应的表中的数据么？如果是的话，那是哪张表或哪几张表呢？

**Comment by lynguo** [comment]
"正在部署,请等待..." 是因为cachecloud没有连接上你的redis服务器,可以在"系统配置管理"里面添加是你的redis服务器的用户名和密码.
