### ISSUE TITLE
导入应用时提示IP不存在

### ISSUE THREAD

**Issue by liurongwei** [sohutv/cachecloud#97]
![20170904152640](https://user-images.githubusercontent.com/1342352/30015963-95b6e9e2-9185-11e7-9cb0-ffe4d1d8e368.png)

**Comment by minminmsn** [comment]
先添加设备，6台服务器添加设备后就可以了。

**Comment by liurongwei** [comment]
![nsi g y0uch9 iqym 4l](https://user-images.githubusercontent.com/1342352/30143011-3cde3108-93b6-11e7-9618-05fd9510e346.png)

机器列表页面居然404

**Comment by minminmsn** [comment]
我知道你是谁了，我找你吧。

**Comment by keithyzk** [comment]
麻烦讲下问题原因和解决方法啊~~~我也遇到了...

**Comment by minminmsn** [comment]
@keithyzk 就是在设备管理哪里先添加设备，后面才能在这里导入应用。

**Comment by keithyzk** [comment]
@minminmsn 感谢~ 已解决

**Comment by keithyzk** [comment]
收到。这个问题已经解决非常感谢~



18923436904@163.com
 
发件人： Jerry Min
发送时间： 2018-07-30 15:58
收件人： sohutv/cachecloud
抄送： keithyzk; Mention
主题： Re: [sohutv/cachecloud] 导入应用时提示IP不存在 (#97)
@keithyzk 就是在设备管理哪里先添加设备，后面才能在这里导入应用。

**Comment by keithyzk** [comment]
你好
我还有个cachecloud的问题想请教一下，我手动启动了几个集群的从节点，如何将这些节点添加到cachecloud现有的一个应用中呢？
昨天找了很久，也没有找到这样的功能。在“应用运维”中选择“添加slave”也是会报错。
如果邮件不方便，麻烦添加QQ: 252256766
万分感谢~



18923436904@163.com
 
发件人： Jerry Min
发送时间： 2018-07-30 15:58
收件人： sohutv/cachecloud
抄送： keithyzk; Mention
主题： Re: [sohutv/cachecloud] 导入应用时提示IP不存在 (#97)
@keithyzk 就是在设备管理哪里先添加设备，后面才能在这里导入应用。
―

**Comment by minminmsn** [comment]
@keithyzk 您好这个问题已经问开发者了，没有这个问题，除非修改数据库等非常麻烦。

**Comment by minminmsn** [comment]
@keithyzk 目前没有这个功能。

**Comment by keithyzk** [comment]
明白~
感谢答疑。



18923436904@163.com
 
发件人： Jerry Min
发送时间： 2018-08-01 11:30
收件人： sohutv/cachecloud
抄送： keithyzk; Mention
主题： Re: [sohutv/cachecloud] 导入应用时提示IP不存在 (#97)
@keithyzk 目前没有这个功能。
