### ISSUE TITLE
简单的nginx+虚ip的web高可用方案是否会遇到性能瓶颈？

### ISSUE THREAD

**Issue by Calabor-Hoc** [sohutv/cachecloud#98]
如果按照wiki中的cachecloud web服务高可用的方案，即keepalive + 虚ip + nginx，是否会遇到下列问题？
1. 当cachecloud管理的redis实例和redis服务器越来越多的时候，监控和统计的quartz任务会越来越多，越来越频繁，cachecloud被多机部署后，每个cachecloud负责的的quartz任务还是一样的。并不会分担压力。

2. 在cachecloud多机部署后，每个cachecloud负责的的quartz任务都是重复的，使用的mysql也是同一个，是否会引发数据库数据读写的死锁？

我所在的公司使用的cachecloud已经管理了50多台机器上的100多个redis实例，以后这个数量可能会扩充十倍，现在使用的是cachecloud单站点模式，以后肯定要改造为高可用，但是比较担心使用wiki中的高可用改造方案后，会遇到上述两个问题

**Comment by carlosfu** [comment]
@Calabor-Hoc 

1. 分担。
2. 不会。可以参考下搜狐的规模
