### ISSUE TITLE
cachecloud先版本能完美兼容redis4.0不？

### ISSUE THREAD

**Issue by LifeFly** [sohutv/cachecloud#99]
cachecloud先版本能完美兼容redis4.0不

**Comment by carlosfu** [comment]
应该可以，有些配置需要兼容下。可以参考下https://cachecloud.github.io/2016/07/13/1.2.%20Redis%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95/ 第三节。

**Comment by LifeFly** [comment]
多谢
